using System.Globalization;
using System.IO.Compression;
using System.Security;
using System.Text;
using EmaBot.Api.Data;
using EmaBot.Api.Models;
using Microsoft.EntityFrameworkCore;

namespace EmaBot.Api.Services;

public static class PaperSessionExcelExport
{
    public static async Task<byte[]?> CreateAsync(EmaBotDbContext database, PaperTradingCoordinator coordinator, int sessionId, CancellationToken token)
    {
        var session = await database.PaperSessions.AsNoTracking().SingleOrDefaultAsync(item => item.Id == sessionId, token);
        if (session is null) return null;
        var symbols = await database.PaperSessionSymbols.AsNoTracking().Where(item => item.PaperSessionId == sessionId).OrderBy(item => item.Id).ToListAsync(token);
        var trades = await database.PaperTrades.AsNoTracking().Where(item => item.PaperSessionId == sessionId).OrderBy(item => item.Id).ToListAsync(token);
        var events = await database.PaperTradeEvents.AsNoTracking().Where(item => item.PaperTrade!.PaperSessionId == sessionId).OrderBy(item => item.PaperTradeId).ThenBy(item => item.TimeUtc).ThenBy(item => item.Id).ToListAsync(token);
        var decisions = await database.PaperDecisionEvents.AsNoTracking().Where(item => item.PaperSessionId == sessionId).OrderBy(item => item.TimeUtc).ThenBy(item => item.Id).ToListAsync(token);
        var runtime = coordinator.GetRuntimeSnapshot() is { } snapshot && snapshot.SessionId == sessionId ? snapshot : null;
        var symbolsById = symbols.ToDictionary(item => item.Id);
        var tradesById = trades.ToDictionary(item => item.Id);
        var openTrades = trades.Count(item => item.Status == PaperTradeStatus.Open);
        var sheets = new List<Sheet>
        {
            new("Session", Fields(("Exported At UTC", DateTimeOffset.UtcNow), ("Session ID", session.Id), ("Market Data Source", session.MarketDataSource), ("Status", session.Status), ("Interval", session.Interval), ("Created At UTC", session.CreatedAtUtc), ("Started At UTC", session.StartedAtUtc), ("Stopped At UTC", session.StoppedAtUtc), ("Interrupted At UTC", session.InterruptedAtUtc), ("Failure Message", session.FailureMessage), ("Account Currency", session.AccountCurrency), ("Starting Balance", session.StartingBalance), ("Current Realized Balance", session.CurrentBalance), ("Used Margin", session.UsedMargin), ("Free Simulated Margin", session.CurrentBalance - session.UsedMargin), ("Realized Net P/L", session.NetPnl), ("Total Trading Costs", session.TotalTradingCosts), ("Completed Trades", session.CompletedTrades), ("Open Trades", openTrades), ("Symbols", symbols.Count), ("Total Crossovers", session.TotalCrossovers), ("Long Signals", session.LongSignals), ("Short Signals", session.ShortSignals), ("Rejected By EMA100", session.RejectedByEma100), ("Rejected By EMA Gap", session.RejectedByEmaGap), ("Rejected By Stop Distance", session.RejectedByStopDistance), ("Rejected By Fees", session.RejectedByFees), ("Rejected By Trading Costs", session.RejectedByTradingCosts), ("Rejected By Insufficient Margin", session.RejectedByInsufficientMargin), ("Rejected By Invalid Volume", session.RejectedByInvalidVolume), ("Rejected By Executable Stop", session.RejectedByExecutableStop), ("Confirmation Failed", session.ConfirmationFailed), ("Invalid Stop Loss", session.InvalidStopLoss), ("Skipped While Position Open", session.SkippedWhilePositionOpen), ("Connection State", runtime?.ConnectionState), ("Last Runtime Update UTC", runtime?.LastUpdateUtc))),
            new("Settings", Fields(("Risk / Reward", session.RiskReward), ("Wait For Confirmation Candle", session.WaitForConfirmationCandle), ("Use EMA100 Filter", session.UseEma100Filter), ("Minimum EMA Gap %", session.MinEmaGapPercent), ("Maximum Stop Distance %", session.MaxStopDistancePercent), ("Adaptive Initial SL", session.UseAdaptiveInitialStop), ("Same Trend Re-entry Enabled", session.SameTrendReentryEnabled), ("Maximum Re-entry Age Bars", session.MaxReentryAgeBars), ("Exit On Opposite Crossover", session.ExitOnOppositeCrossover), ("Trailing Stop", session.TrailingStopEnabled), ("Paper Position Sizing Mode", session.PaperPositionSizingMode), ("Paper Fixed Lots", session.PaperFixedLots), ("Paper Margin Per Trade %", session.PaperMarginPerTradePercent), ("Paper Starting Balance", session.StartingBalance), ("Account Currency", session.AccountCurrency), ("Legacy Fixed Order Size USDT", session.FixedOrderSizeUsdt), ("Legacy Position Sizing Mode", session.PositionSizingMode), ("Legacy Starting Balance USDT", session.StartingBalanceUsdt), ("Legacy Margin Per Trade %", session.MarginPerTradePercent), ("Legacy Leverage", session.Leverage), ("Legacy Fee Percent Per Side", session.FeePercentPerSide))),
            new("Symbols", SymbolRows(symbols, runtime, trades)),
            new("Trades", TradeRows(session, trades, runtime)),
            new("Trade Events", EventRows(events, tradesById)),
            new("Decisions", DecisionRows(decisions, symbolsById))
        };
        return Workbook(sheets);
    }

    private static IEnumerable<object?[]> Fields(params (string Field, object? Value)[] fields) => [new object?[] { "Field", "Value" }, .. fields.Select(item => new object?[] { item.Field, item.Value })];
    private static IEnumerable<object?[]> SymbolRows(IReadOnlyList<PaperSessionSymbol> symbols, PaperRuntimeSnapshot? runtime, IReadOnlyList<PaperTrade> trades)
    {
        var header = new object?[] { "Session Symbol ID", "Symbol", "Broker Symbol", "Contract Size", "Volume Minimum", "Volume Maximum", "Volume Step", "Volume Limit", "Tick Size", "Tick Value Profit", "Tick Value Loss", "Point Size", "Stops Level Points", "Trade Mode", "Commission Per Lot Per Side", "Last Processed Closed Candle UTC", "Last Market Event UTC", "Last Known Price", "Trend Regime Direction", "Trend Regime Crossover UTC", "Re-entry Eligible", "Re-entry Consumed", "Latest Bid", "Latest Ask", "Latest Spread", "Last Evaluated Candle UTC", "Trend", "EMA9", "EMA15", "EMA100", "EMA Gap %", "Gap State", "Current Executable Exit Price", "Open Trade ID", "Pending Direction", "Pending Crossover UTC", "Pending Signal UTC", "Pending Stop Price", "Pending Stop Source", "Pending Stop Source Time UTC", "Pending Signal Open", "Pending Signal Close", "Pending EMA9", "Pending EMA15", "Pending EMA100", "Pending Gap %", "Pending Gap State", "Pending Is Re-entry", "Pending Trend Regime Crossover UTC", "Pending ATR14", "Pending Reversal Power", "Pending Reversal Power Band", "Pending Stop Anchor", "Pending Stop Buffer", "Pending Opposite Exit Direction", "Pending Opposite Exit Signal UTC" };
        return new[] { header }.Concat(symbols.Select(symbol =>
        {
            PaperSymbolRuntimeSnapshot? live = null; if (runtime is not null) runtime.Symbols.TryGetValue(symbol.Symbol, out live); var indicator = live?.Indicator; var open = live?.OpenTrade ?? trades.SingleOrDefault(trade => trade.PaperSessionSymbolId == symbol.Id && trade.Status == PaperTradeStatus.Open); var bid = live?.LatestBid; var ask = live?.LatestAsk;
            return new object?[] { symbol.Id, symbol.Symbol, symbol.BrokerSymbol, symbol.ContractSize, symbol.VolumeMin, symbol.VolumeMax, symbol.VolumeStep, symbol.VolumeLimit, symbol.TickSize, symbol.TickValueProfit, symbol.TickValueLoss, symbol.PointSize, symbol.StopsLevelPoints, symbol.TradeMode, symbol.CommissionPerLotPerSide, symbol.LastProcessedClosedCandleUtc, symbol.LastMarketEventUtc, symbol.LastKnownPrice, symbol.TrendRegimeDirection, symbol.TrendRegimeCrossoverTimeUtc, symbol.ReentryEligible, symbol.ReentryConsumed, bid, ask, bid is not null && ask is not null ? ask - bid : null, indicator?.Time, indicator?.TrendDirection, indicator?.Ema9, indicator?.Ema15, indicator?.Ema100, indicator?.GapPercent, indicator?.GapState, open is null ? null : open.Direction == Strategy.SignalDirection.Long ? bid : ask, open?.Id, symbol.PendingDirection, symbol.PendingCrossoverTimeUtc, symbol.PendingSignalTimeUtc, symbol.PendingStopPrice, symbol.PendingStopSourceType, symbol.PendingStopSourceTimeUtc, symbol.PendingSignalOpen, symbol.PendingSignalClose, symbol.PendingSignalEma9, symbol.PendingSignalEma15, symbol.PendingSignalEma100, symbol.PendingSignalGapPercent, symbol.PendingSignalGapState, symbol.PendingIsReentry, symbol.PendingTrendRegimeCrossoverTimeUtc, symbol.PendingSignalAtr14, symbol.PendingReversalPowerScore, symbol.PendingReversalPowerBand, symbol.PendingStopAnchorPrice, symbol.PendingStopBuffer, symbol.PendingOppositeExitDirection, symbol.PendingOppositeExitSignalTimeUtc };
        }));
    }
    private static IEnumerable<object?[]> TradeRows(PaperSession session, IReadOnlyList<PaperTrade> trades, PaperRuntimeSnapshot? runtime)
    {
        var header = new object?[] { "Trade ID", "Session ID", "Session Symbol ID", "Symbol", "Interval", "Status", "Direction", "Is Re-entry", "Trend Regime Crossover UTC", "Re-entry Age Bars", "Crossover UTC", "Signal UTC", "Entry UTC", "Exit UTC", "Entry Price", "Exit Price", "Quantity / Exposure", "Lots", "Entry Bid", "Entry Ask", "Entry Spread", "Spread / Initial Risk %", "Exit Bid", "Exit Ask", "Exit Spread", "Required Margin", "Margin Used", "Account Equity At Entry", "Initial SL", "Current SL", "Final SL", "Stop Source", "Stop Source Time UTC", "Original TP", "Current TP", "Final TP", "TP Extended", "Exit Reason", "Gross P/L", "Round-trip Commission", "Net P/L", "Net P/L %", "Account Currency", "MFE Excursion", "MFE %", "MAE Excursion", "MAE %", "Best Favorable Progress %", "Signal Open", "Signal Close", "Signal EMA9", "Signal EMA15", "Signal EMA100", "Signal Gap %", "Signal Gap State", "Adaptive Initial SL", "Signal ATR14", "Reversal Power", "Reversal Power Band", "Stop Anchor", "Stop Buffer", "Current Executable Exit Price", "Current Gross P/L", "Current Net P/L", "Current P/L % On Margin", "Current P/L Valuation UTC", "Current P/L Available", "Legacy Gross P/L USDT", "Legacy Net P/L USDT", "Legacy Fees USDT" };
        return new[] { header }.Concat(trades.Select(trade =>
        {
            PaperSymbolRuntimeSnapshot? live = null; if (runtime is not null) runtime.Symbols.TryGetValue(trade.Symbol, out live); var active = live?.OpenTrade?.Id == trade.Id ? live : null; var currentExit = active is null ? null : trade.Direction == Strategy.SignalDirection.Long ? active.LatestBid : active.LatestAsk;
            var closed = trade.Status == PaperTradeStatus.Closed; var hideLegacyResult = !closed && session.MarketDataSource == MarketDataSource.Mt5Exness;
            var initialRisk = decimal.Abs(trade.EntryPrice - trade.InitialStopLoss);
            decimal? spreadToRisk = trade.EntrySpread is { } spread && initialRisk > 0m ? spread / initialRisk * 100m : null;
            return new object?[] { trade.Id, session.Id, trade.PaperSessionSymbolId, trade.Symbol, trade.Interval, trade.Status, trade.Direction, trade.IsReentry, trade.TrendRegimeCrossoverTimeUtc, trade.ReentryAgeBars, trade.CrossoverTimeUtc, trade.SignalTimeUtc, trade.EntryTimeUtc, closed ? trade.ExitTimeUtc : null, trade.EntryPrice, closed ? trade.ExitPrice : null, trade.Quantity, trade.Lots, trade.EntryBid, trade.EntryAsk, trade.EntrySpread, spreadToRisk, closed ? trade.ExitBid : null, closed ? trade.ExitAsk : null, closed ? trade.ExitSpread : null, trade.RequiredMargin, trade.MarginUsed, trade.AccountEquityAtEntry, trade.InitialStopLoss, trade.CurrentStopLoss, closed ? trade.FinalStopLoss : null, trade.StopSourceType, trade.StopSourceTimeUtc, trade.OriginalTakeProfit, trade.CurrentTakeProfit, closed ? trade.FinalTakeProfit : null, trade.TakeProfitExtended, closed ? trade.ExitReason : null, closed ? trade.GrossPnl : null, trade.RoundTripCommission, closed ? trade.NetPnl : null, closed ? trade.NetPnlPercent : null, session.AccountCurrency, trade.MfePrice, trade.MfePercent, trade.MaePrice, trade.MaePercent, trade.BestFavorableProgressPercent, trade.SignalOpen, trade.SignalClose, trade.SignalEma9, trade.SignalEma15, trade.SignalEma100, trade.SignalGapPercent, trade.SignalGapState, trade.UseAdaptiveInitialStop, trade.SignalAtr14, trade.ReversalPowerScore, trade.ReversalPowerBand, trade.StopAnchorPrice, trade.StopBuffer, currentExit, active?.CurrentGrossPnl, active?.CurrentNetPnl, active?.CurrentPnlPercent, active?.CurrentPnlCalculatedAtUtc, active?.CurrentPnlAvailable, hideLegacyResult ? null : trade.GrossPnlUsdt, hideLegacyResult ? null : trade.NetPnlUsdt, hideLegacyResult && trade.TotalFeesUsdt == 0m ? null : trade.TotalFeesUsdt };
        }));
    }
    private static IEnumerable<object?[]> EventRows(IReadOnlyList<PaperTradeEvent> events, IReadOnlyDictionary<int, PaperTrade> trades) => new[] { new object?[] { "Event ID", "Trade ID", "Symbol", "Direction", "Time UTC", "Type", "Market Price", "Old SL", "New SL", "Old TP", "New TP", "Progress %" } }.Concat(events.Select(item => { var trade = trades[item.PaperTradeId]; return new object?[] { item.Id, item.PaperTradeId, trade.Symbol, trade.Direction, item.TimeUtc, item.Type, item.MarketPrice, item.OldStop, item.NewStop, item.OldTakeProfit, item.NewTakeProfit, item.ProgressPercent }; }));
    private static IEnumerable<object?[]> DecisionRows(IReadOnlyList<PaperDecisionEvent> decisions, IReadOnlyDictionary<int, PaperSessionSymbol> symbols) => new[] { new object?[] { "Decision ID", "Session Symbol ID", "Symbol", "Time UTC", "Candle Close UTC", "Stage", "Direction", "Message", "EMA9", "EMA15", "EMA100", "Gap %", "Gap State", "Stop Price", "Stop Source", "Expected Entry Open UTC", "Bid", "Ask", "Entry Price", "Lots", "Required Margin" } }.Concat(decisions.Select(item => new object?[] { item.Id, item.PaperSessionSymbolId, symbols[item.PaperSessionSymbolId].Symbol, item.TimeUtc, item.CandleCloseTimeUtc, item.Stage, item.Direction, item.Message, item.Ema9, item.Ema15, item.Ema100, item.GapPercent, item.GapState, item.StopPrice, item.StopSource, item.ExpectedEntryOpenUtc, item.Bid, item.Ask, item.EntryPrice, item.Lots, item.RequiredMargin }));

    private sealed record Sheet(string Name, IEnumerable<object?[]> Rows);
    private static byte[] Workbook(IReadOnlyList<Sheet> sheets)
    {
        using var stream = new MemoryStream(); using (var zip = new ZipArchive(stream, ZipArchiveMode.Create, true))
        {
            Write(zip, "[Content_Types].xml", "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>" + string.Concat(Enumerable.Range(1, sheets.Count).Select(i => $"<Override PartName=\"/xl/worksheets/sheet{i}.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>")) + "</Types>");
            Write(zip, "_rels/.rels", "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");
            Write(zip, "xl/workbook.xml", "<?xml version=\"1.0\" encoding=\"UTF-8\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets>" + string.Concat(sheets.Select((sheet, i) => $"<sheet name=\"{SecurityElement.Escape(sheet.Name)}\" sheetId=\"{i + 1}\" r:id=\"rId{i + 1}\"/>")) + "</sheets></workbook>");
            Write(zip, "xl/_rels/workbook.xml.rels", "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" + string.Concat(Enumerable.Range(1, sheets.Count).Select(i => $"<Relationship Id=\"rId{i}\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet{i}.xml\"/>")) + "</Relationships>");
            foreach (var (sheet, index) in sheets.Select((sheet, index) => (sheet, index))) Write(zip, $"xl/worksheets/sheet{index + 1}.xml", Worksheet(sheet.Rows));
        }
        return stream.ToArray();
    }
    private static string Worksheet(IEnumerable<object?[]> rows) { var xml = new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>"); foreach (var row in rows) { xml.Append("<row>"); foreach (var value in row) Cell(xml, value); xml.Append("</row>"); } return xml.Append("</sheetData></worksheet>").ToString(); }
    private static void Cell(StringBuilder xml, object? value) { if (value is null) { xml.Append("<c/>"); return; } if (value is DateTimeOffset time) { xml.Append("<c t=\"inlineStr\"><is><t>").Append(time.ToString("O", CultureInfo.InvariantCulture)).Append("</t></is></c>"); return; } if (value is decimal or int) { xml.Append("<c><v>").Append(Convert.ToString(value, CultureInfo.InvariantCulture)).Append("</v></c>"); return; } if (value is bool flag) { xml.Append("<c t=\"b\"><v>").Append(flag ? '1' : '0').Append("</v></c>"); return; } xml.Append("<c t=\"inlineStr\"><is><t>").Append(SecurityElement.Escape(Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty)).Append("</t></is></c>"); }
    private static void Write(ZipArchive archive, string path, string text) { using var writer = new StreamWriter(archive.CreateEntry(path).Open(), new UTF8Encoding(false)); writer.Write(text); }
}
