using System.Globalization;
using System.IO.Compression;
using System.Security;
using System.Text;
using System.Diagnostics;
using EmaBot.Api.Data;
using EmaBot.Api.Market;
using EmaBot.Api.Models;
using EmaBot.Api.Strategy;
using Microsoft.EntityFrameworkCore;

namespace EmaBot.Api.Services;

public sealed record RegimeTradeDiagnostic(string Symbol, string Timeframe, BacktestTrade Trade, decimal? Ema9Slope5Percent, decimal? Ema15Slope5Percent, decimal? Ema100Slope5Percent, decimal? Ema100Slope20Percent, decimal? DistanceFromEma100Percent, decimal? PriceReturn20Percent, decimal? Atr14Percent, decimal? TrendEfficiency20, bool? Ema100Slope5Aligned, bool? Ema100Slope20Aligned, bool? PriceVsEma100Aligned, HigherTimeframeDiagnostic HigherTimeframe);
public sealed record RegimeExportData(StrategyOptimizationRun Run, StrategyOptimizationCandidate Candidate, IReadOnlyList<RegimeTradeDiagnostic> Trades);

public sealed class StrategyRegimeDiagnosticsService(EmaBotDbContext database, IHistoricalMarketDataProvider historical, BacktestEngine engine, ILogger<StrategyRegimeDiagnosticsService>? logger = null)
{
    public async Task<RegimeExportData?> CreateAsync(int runId, int candidateId, CancellationToken token)
    {
        var run = await database.StrategyOptimizationRuns.AsNoTracking().SingleOrDefaultAsync(value => value.Id == runId, token);
        if (run is null || run.Status != StrategyOptimizationStatus.Completed) return null;
        var candidate = await database.StrategyOptimizationCandidates.AsNoTracking().SingleOrDefaultAsync(value => value.Id == candidateId && value.StrategyOptimizationRunId == runId, token);
        if (candidate is null) return null;
        var settings = Settings(candidate, run); var symbols = System.Text.Json.JsonSerializer.Deserialize<string[]>(run.SymbolsJson) ?? []; var frames = System.Text.Json.JsonSerializer.Deserialize<string[]>(run.TimeframesJson) ?? []; var result = new List<RegimeTradeDiagnostic>(); var cache = new Dictionary<(string Symbol, string Frame), Candle[]>(); var fetchDuration = TimeSpan.Zero; var diagnosticDuration = TimeSpan.Zero;
        foreach (var symbol in symbols) foreach (var frame in frames)
        {
            token.ThrowIfCancellationRequested(); var fetch = Stopwatch.StartNew(); var candles = await CandlesAsync(symbol, frame, run, cache, token);
            var htf = HigherTimeframe(frame); var htfCandles = htf is null ? null : await CandlesAsync(symbol, htf, run, cache, token); fetch.Stop(); fetchDuration += fetch.Elapsed;
            var diagnostics = Stopwatch.StartNew(); var context = settings.UseHtfRegimeFilter ? new StrategyMarketContext(candles, htf, htfCandles) : null; var calculation = engine.RunResearch(candles, settings, run.RequestedStartUtc, run.RequestedEndUtc, context); result.AddRange(Describe(symbol, frame, candles, calculation.Trades, htf, htfCandles)); diagnostics.Stop(); diagnosticDuration += diagnostics.Elapsed;
        }
        var uniqueHtfMarkets = symbols.SelectMany(symbol => frames.Select(frame => (Symbol: symbol, Frame: HigherTimeframe(frame)))).Where(value => value.Frame is not null).Distinct().Count();
        logger?.LogInformation("Regime diagnostics run {RunId}, candidate {CandidateId}: {ExecutionMarkets} execution markets, {UniqueHtfMarkets} unique HTF markets, candle fetch {FetchDuration}, diagnostics {DiagnosticDuration}, {TradeCount} trades.", runId, candidateId, symbols.Length * frames.Length, uniqueHtfMarkets, fetchDuration, diagnosticDuration, result.Count);
        return new(run, candidate, result);
    }

    private async Task<Candle[]> CandlesAsync(string symbol, string frame, StrategyOptimizationRun run, IDictionary<(string Symbol, string Frame), Candle[]> cache, CancellationToken token)
    {
        if (cache.TryGetValue((symbol, frame), out var values)) return values;
        values = (await historical.GetRangeAsync(symbol, frame, run.RequestedStartUtc - Warmup(frame), run.RequestedEndUtc, token)).Where(candle => candle.IsClosed).OrderBy(candle => candle.CloseTimeUtc).ToArray(); cache[(symbol, frame)] = values; return values;
    }

    public static string? HigherTimeframe(string timeframe) => HigherTimeframeRegime.ForExecutionTimeframe(timeframe);

    public static IReadOnlyList<RegimeTradeDiagnostic> Describe(string symbol, string timeframe, IReadOnlyList<Candle> input, IEnumerable<BacktestTrade> trades, string? htfTimeframe = null, IReadOnlyList<Candle>? htfInput = null)
    {
        var candles = input.Where(candle => candle.IsClosed).OrderBy(candle => candle.CloseTimeUtc).ToArray(); var closes = candles.Select(candle => candle.Close).ToArray(); var ema9 = EmaCalculator.Calculate(closes, 9); var ema15 = EmaCalculator.Calculate(closes, 15); var ema100 = EmaCalculator.Calculate(closes, 100);
        return trades.Select(trade => { var index = Array.FindIndex(candles, candle => candle.CloseTimeUtc == trade.SignalTimeUtc); return new RegimeTradeDiagnostic(symbol, timeframe, trade, Slope(ema9,index,5), Slope(ema15,index,5), Slope(ema100,index,5), Slope(ema100,index,20), Percent(trade.SignalClose, ema100.ElementAtOrDefault(index)), Return(closes,index,20), Atr(candles,index), Efficiency(closes,index), Align(Slope(ema100,index,5),trade.Direction), Align(Slope(ema100,index,20),trade.Direction), AlignPrice(trade.SignalClose,ema100.ElementAtOrDefault(index),trade.Direction), DescribeHigherTimeframe(trade, htfTimeframe, htfInput)); }).ToArray();
    }

    public static HigherTimeframeDiagnostic DescribeHigherTimeframe(BacktestTrade trade, string? timeframe, IReadOnlyList<Candle>? input) => HigherTimeframeRegime.Calculate(trade.SignalTimeUtc, trade.Direction, timeframe, input);

    private static decimal? Slope(IReadOnlyList<decimal?> values, int index, int bars) => index < bars || !values.ElementAtOrDefault(index).HasValue || !values[index-bars].HasValue || values[index-bars] == 0 ? null : (values[index]!.Value-values[index-bars]!.Value)/values[index-bars]!.Value*100m;
    private static decimal? Percent(decimal value, decimal? baseValue) => !baseValue.HasValue || baseValue == 0 ? null : (value-baseValue.Value)/baseValue.Value*100m;
    private static decimal? Return(decimal[] values, int index, int bars) => index < bars || values[index-bars] == 0 ? null : (values[index]-values[index-bars])/values[index-bars]*100m;
    private static decimal? Atr(Candle[] candles, int index) { if(index < 14 || candles[index].Close == 0) return null; decimal total=0; for(var i=index-13;i<=index;i++){var previous=candles[i-1].Close; total+=Math.Max(candles[i].High-candles[i].Low,Math.Max(decimal.Abs(candles[i].High-previous),decimal.Abs(candles[i].Low-previous)));} return total/14m/candles[index].Close*100m; }
    private static decimal? Efficiency(decimal[] values, int index) { if(index<20) return null; decimal denominator=0; for(var i=index-19;i<=index;i++) denominator+=decimal.Abs(values[i]-values[i-1]); return denominator==0?null:decimal.Abs(values[index]-values[index-20])/denominator; }
    private static bool? Align(decimal? slope, SignalDirection direction) => !slope.HasValue ? null : direction == SignalDirection.Long ? slope > 0 : slope < 0;
    private static bool AlignFast(decimal ema9, decimal ema15, SignalDirection direction) => direction == SignalDirection.Long ? ema9 > ema15 : ema9 < ema15;
    private static bool? AlignPrice(decimal close, decimal? ema, SignalDirection direction) => !ema.HasValue ? null : direction == SignalDirection.Long ? close > ema : close < ema;
    private static TimeSpan Warmup(string frame) => frame switch { "3m"=>TimeSpan.FromMinutes(600),"5m"=>TimeSpan.FromMinutes(1000),"15m"=>TimeSpan.FromMinutes(3000),"30m"=>TimeSpan.FromMinutes(6000),"1h"=>TimeSpan.FromHours(200),"2h"=>TimeSpan.FromHours(400),"4h"=>TimeSpan.FromHours(800),"6h"=>TimeSpan.FromHours(1200),"8h"=>TimeSpan.FromHours(1600),"12h"=>TimeSpan.FromHours(2400),"1d"=>TimeSpan.FromDays(200),"3d"=>TimeSpan.FromDays(600),"1w"=>TimeSpan.FromDays(1400),_=>TimeSpan.FromDays(6200) };
    private static TradingSettings Settings(StrategyOptimizationCandidate candidate, StrategyOptimizationRun run) => new(){Id=1,RiskReward=candidate.RiskReward,MinEmaGapPercent=candidate.MinEmaGapPercent,MaxStopDistancePercent=candidate.MaxStopDistancePercent,WaitForConfirmationCandle=candidate.WaitForConfirmationCandle,UseEma100Filter=candidate.UseEma100Filter,UseHtfRegimeFilter=candidate.UseHtfRegimeFilter,TrailingStopEnabled=candidate.TrailingStopEnabled,SimulatedAccountBalanceUsdt=run.SimulatedAccountBalanceUsdt,FixedOrderSizeUsdt=run.FixedOrderSizeUsdt,MarginPerTradePercent=run.MarginPerTradePercent,Leverage=run.Leverage,FeePercentPerSide=run.FeePercentPerSide,PositionSizingMode=run.PositionSizingMode};
}

public static class StrategyRegimeWorkbook
{
    // Match optimizer reporting: fee-aware exits can leave decimal dust around zero.
    private const decimal BreakEvenToleranceUsdt = 0.000000000001m;
    public static byte[] Create(RegimeExportData data)
    {
        var sheets = new List<(string, IEnumerable<IEnumerable<string?>>)> { ("Overview", Overview(data)), ("Trade Diagnostics", Diagnostics(data)), ("By Symbol", Aggregate(data.Trades, value=>value.Symbol)), ("By Timeframe", Aggregate(data.Trades,value=>value.Timeframe)), ("By Direction", Aggregate(data.Trades,value=>value.Trade.Direction.ToString())), ("Alignment Summary", Alignment(data)), ("HTF Alignment Summary", HtfAlignment(data)), ("HTF Summary", HtfSummary(data)) };
        using var stream=new MemoryStream(); using(var zip=new ZipArchive(stream,ZipArchiveMode.Create,true)){ Write(zip,"[Content_Types].xml","<?xml version=\"1.0\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>"+string.Concat(Enumerable.Range(1,sheets.Count).Select(i=>$"<Override PartName=\"/xl/worksheets/sheet{i}.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>"))+"</Types>"); Write(zip,"_rels/.rels","<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>"); Write(zip,"xl/workbook.xml","<?xml version=\"1.0\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets>"+string.Concat(sheets.Select((s,i)=>$"<sheet name=\"{s.Item1}\" sheetId=\"{i+1}\" r:id=\"rId{i+1}\"/>"))+"</sheets></workbook>"); Write(zip,"xl/_rels/workbook.xml.rels","<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">"+string.Concat(Enumerable.Range(1,sheets.Count).Select(i=>$"<Relationship Id=\"rId{i}\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet{i}.xml\"/>"))+"</Relationships>"); foreach(var(s,i) in sheets.Select((s,i)=>(s,i+1))) Sheet(zip,$"xl/worksheets/sheet{i}.xml",s.Item2); } return stream.ToArray();
    }
    private static IEnumerable<IEnumerable<string?>> Overview(RegimeExportData d) => [["Run ID",S(d.Run.Id)],["Candidate ID",S(d.Candidate.Id)],["Period",$"{d.Run.RequestedStartUtc:O} to {d.Run.RequestedEndUtc:O}"],["Symbols",d.Run.SymbolsJson],["Timeframes",d.Run.TimeframesJson],["Full trades",S(d.Trades.Count)],["Gross PnL",S(d.Trades.Sum(x=>x.Trade.GrossPnlUsdt))],["Fees",S(d.Trades.Sum(x=>x.Trade.TotalFeesUsdt))],["Net PnL",S(d.Trades.Sum(x=>x.Trade.NetPnlUsdt))],["Net PF",S(Pf(d.Trades))]];
    private static IEnumerable<IEnumerable<string?>> Diagnostics(RegimeExportData d) => new[]{ new[]{"Symbol","Timeframe","Direction","IsReentry","CrossoverTimeUtc","SignalTimeUtc","EntryTimeUtc","ExitTimeUtc","ExitReason","GrossPnlUsdt","TotalFeesUsdt","NetPnlUsdt","NetRMultiple","MfePercent","MaePercent","HoldingMinutes","SignalClose","SignalEma9","SignalEma15","SignalEma100","SignalGapPercent","EMA9Slope5","EMA15Slope5","EMA100Slope5","EMA100Slope20","DistanceFromEMA100","PriceReturn20","ATR14Percent","TrendEfficiency20","EMA100Slope5Aligned","EMA100Slope20Aligned","PriceVsEMA100Aligned","HtfTimeframe","HtfCandleCloseTimeUtc","HtfAgeMinutes","HtfClose","HtfEma9","HtfEma15","HtfEma100","HtfEmaGapPercent","HtfEma9Slope5Percent","HtfEma15Slope5Percent","HtfEma100Slope5Percent","HtfEma100Slope20Percent","HtfDistanceFromEma100Percent","HtfPriceReturn20Percent","HtfAtr14Percent","HtfTrendEfficiency20","HtfFastTrend","HtfFastTrendAligned","HtfPriceVsEma100Aligned","HtfEma100Slope5Aligned","HtfEma100Slope20Aligned","HtfFullTrendAligned"} }.Concat(d.Trades.Select(x=> { var h=x.HigherTimeframe; return new[]{x.Symbol,x.Timeframe,x.Trade.Direction.ToString(),S(x.Trade.IsReentry),S(x.Trade.CrossoverTimeUtc),S(x.Trade.SignalTimeUtc),S(x.Trade.EntryTimeUtc),S(x.Trade.ExitTimeUtc),x.Trade.ExitReason.ToString(),S(x.Trade.GrossPnlUsdt),S(x.Trade.TotalFeesUsdt),S(x.Trade.NetPnlUsdt),S(x.Trade.NetRMultiple),S(x.Trade.MfePercent),S(x.Trade.MaePercent),S((x.Trade.ExitTimeUtc-x.Trade.EntryTimeUtc).TotalMinutes),S(x.Trade.SignalClose),S(x.Trade.SignalEma9),S(x.Trade.SignalEma15),S(x.Trade.SignalEma100),S(x.Trade.SignalGapPercent),S(x.Ema9Slope5Percent),S(x.Ema15Slope5Percent),S(x.Ema100Slope5Percent),S(x.Ema100Slope20Percent),S(x.DistanceFromEma100Percent),S(x.PriceReturn20Percent),S(x.Atr14Percent),S(x.TrendEfficiency20),S(x.Ema100Slope5Aligned),S(x.Ema100Slope20Aligned),S(x.PriceVsEma100Aligned),S(h.Timeframe),S(h.CandleCloseTimeUtc),S(h.AgeMinutes),S(h.Close),S(h.Ema9),S(h.Ema15),S(h.Ema100),S(h.EmaGapPercent),S(h.Ema9Slope5Percent),S(h.Ema15Slope5Percent),S(h.Ema100Slope5Percent),S(h.Ema100Slope20Percent),S(h.DistanceFromEma100Percent),S(h.PriceReturn20Percent),S(h.Atr14Percent),S(h.TrendEfficiency20),S(h.FastTrend),S(h.FastTrendAligned),S(h.PriceVsEma100Aligned),S(h.Ema100Slope5Aligned),S(h.Ema100Slope20Aligned),S(h.FullTrendAligned)}; }));
    private static IEnumerable<IEnumerable<string?>> Aggregate(IEnumerable<RegimeTradeDiagnostic> trades, Func<RegimeTradeDiagnostic,string> key) => new[]{new[]{"Group","Trades","Long Trades","Short Trades","Gross","Fees","Net","Net PF","Win %","Average Net R"}}.Concat(trades.GroupBy(key).Select(g=>new[]{g.Key,S(g.Count()),S(g.Count(x=>x.Trade.Direction==SignalDirection.Long)),S(g.Count(x=>x.Trade.Direction==SignalDirection.Short)),S(g.Sum(x=>x.Trade.GrossPnlUsdt)),S(g.Sum(x=>x.Trade.TotalFeesUsdt)),S(g.Sum(x=>x.Trade.NetPnlUsdt)),S(Pf(g)),S(g.Count()==0?0m:(decimal)g.Count(x=>x.Trade.NetPnlUsdt>0)/g.Count()*100m),S(g.Average(x=>x.Trade.NetRMultiple))}));
    private static IEnumerable<IEnumerable<string?>> Alignment(RegimeExportData d) => new[]{new[]{"Diagnostic","Aligned","Trades","Gross","Fees","Net","Net PF","Win %"}}.Concat(new[]{("EMA100Slope5Aligned",d.Trades.Select(x=>x.Ema100Slope5Aligned)),("EMA100Slope20Aligned",d.Trades.Select(x=>x.Ema100Slope20Aligned)),("PriceVsEMA100Aligned",d.Trades.Select(x=>x.PriceVsEma100Aligned))}.SelectMany(set=>new[]{true,false}.Select(value=>{var t=d.Trades.Where((x,i)=>set.Item2.ElementAt(i)==value).ToArray();return new[]{set.Item1,S(value),S(t.Length),S(t.Sum(x=>x.Trade.GrossPnlUsdt)),S(t.Sum(x=>x.Trade.TotalFeesUsdt)),S(t.Sum(x=>x.Trade.NetPnlUsdt)),S(Pf(t)),S(t.Length==0?0m:(decimal)t.Count(x=>x.Trade.NetPnlUsdt>0)/t.Length*100m)};})));
    private static IEnumerable<IEnumerable<string?>> HtfAlignment(RegimeExportData d) => new[]{new[]{"Diagnostic","State","Trades","Winning Trades","Losing Trades","Win %","Gross PnL","Fees","Net PnL","Net PF","Average Net R"}}.Concat(new[]{("HtfFastTrendAligned",d.Trades.Select(x=>x.HigherTimeframe.FastTrendAligned)),("HtfPriceVsEma100Aligned",d.Trades.Select(x=>x.HigherTimeframe.PriceVsEma100Aligned)),("HtfEma100Slope5Aligned",d.Trades.Select(x=>x.HigherTimeframe.Ema100Slope5Aligned)),("HtfEma100Slope20Aligned",d.Trades.Select(x=>x.HigherTimeframe.Ema100Slope20Aligned)),("HtfFullTrendAligned",d.Trades.Select(x=>x.HigherTimeframe.FullTrendAligned))}.SelectMany(set=>new bool?[]{true,false,null}.Select(value=>SummaryRow(set.Item1,value is null?"Unknown":value.Value?"Aligned":"Not Aligned",d.Trades.Where((x,i)=>set.Item2.ElementAt(i)==value)))));
    private static IEnumerable<IEnumerable<string?>> HtfSummary(RegimeExportData d) => new[]{new[]{"Execution Timeframe","HTF Timeframe","Direction","Trades","Win %","Gross","Fees","Net","Net PF","Average Net R"}}.Concat(d.Trades.Where(x=>x.HigherTimeframe.Timeframe is not null).GroupBy(x=>new{x.Timeframe,Htf=x.HigherTimeframe.Timeframe,Direction=x.Trade.Direction}).OrderBy(g=>g.Key.Timeframe).ThenBy(g=>g.Key.Htf).ThenBy(g=>g.Key.Direction).Select(g=>new[]{g.Key.Timeframe,g.Key.Htf,g.Key.Direction.ToString(),S(g.Count()),S(WinRate(g)),S(g.Sum(x=>x.Trade.GrossPnlUsdt)),S(g.Sum(x=>x.Trade.TotalFeesUsdt)),S(g.Sum(x=>x.Trade.NetPnlUsdt)),S(Pf(g)),S(g.Average(x=>x.Trade.NetRMultiple))}));
    private static IEnumerable<string?> SummaryRow(string diagnostic,string state,IEnumerable<RegimeTradeDiagnostic> values){var t=values.ToArray();return new string?[]{diagnostic,state,S(t.Length),S(t.Count(IsWin)),S(t.Count(IsLoss)),S(WinRate(t)),S(t.Sum(x=>x.Trade.GrossPnlUsdt)),S(t.Sum(x=>x.Trade.TotalFeesUsdt)),S(t.Sum(x=>x.Trade.NetPnlUsdt)),S(Pf(t)),S(t.Length==0?0m:t.Average(x=>x.Trade.NetRMultiple))};}
    private static bool IsWin(RegimeTradeDiagnostic value) => value.Trade.NetPnlUsdt > BreakEvenToleranceUsdt;
    private static bool IsLoss(RegimeTradeDiagnostic value) => value.Trade.NetPnlUsdt < -BreakEvenToleranceUsdt;
    private static decimal WinRate(IEnumerable<RegimeTradeDiagnostic> values) { var trades = values.ToArray(); return trades.Length == 0 ? 0m : (decimal)trades.Count(IsWin) / trades.Length * 100m; }
    private static decimal? Pf(IEnumerable<RegimeTradeDiagnostic> values){var a=values.Where(IsWin).Sum(x=>x.Trade.NetPnlUsdt);var b=-values.Where(IsLoss).Sum(x=>x.Trade.NetPnlUsdt);return b==0?a>0?decimal.MaxValue:null:a/b;} private static string? S(object? value)=>value switch {null=>null,DateTimeOffset date=>date.ToString("O",CultureInfo.InvariantCulture),IFormattable formattable=>formattable.ToString(null,CultureInfo.InvariantCulture),_=>value.ToString()};
    private static void Write(ZipArchive z,string n,string t){using var w=new StreamWriter(z.CreateEntry(n).Open(),Encoding.UTF8);w.Write(t);} private static void Sheet(ZipArchive z,string n,IEnumerable<IEnumerable<string?>> rows){using var w=new StreamWriter(z.CreateEntry(n).Open(),Encoding.UTF8);w.Write("<?xml version=\"1.0\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>");foreach(var row in rows){w.Write("<row>");foreach(var v in row){w.Write("<c t=\"inlineStr\"><is><t>");w.Write(SecurityElement.Escape(v??""));w.Write("</t></is></c>");}w.Write("</row>");}w.Write("</sheetData></worksheet>");}
}
