import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import type { BacktestRun, MonitoredSymbol } from '../api'
import { getBacktest, getBacktests, getMonitoredSymbols, runBacktest } from '../api'

const intervals = ['3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h', '12h', '1d', '3d', '1w', '1M']
export function BacktestsPage() {
  const [symbols, setSymbols] = useState<MonitoredSymbol[]>([]); const [runs, setRuns] = useState<BacktestRun[]>([]); const [selected, setSelected] = useState<BacktestRun | null>(null); const [symbol, setSymbol] = useState(''); const [interval, setInterval] = useState('30m'); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  async function refresh() { const [saved, history] = await Promise.all([getMonitoredSymbols(), getBacktests()]); setSymbols(saved.filter(item => item.isEnabled)); setRuns(history) }
  useEffect(() => { void refresh().catch(e => setError(e instanceof Error ? e.message : 'Could not load backtests.')) }, [])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!symbol || !start || !end) return; setBusy(true); setError(null); try { const run = await runBacktest({ symbol, interval, startUtc: `${start}T00:00:00.000Z`, endUtc: `${end}T23:59:59.999Z` }); setSelected(run); await refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Backtest failed.') } finally { setBusy(false) } }
  async function open(id: number) { try { setSelected(await getBacktest(id)) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load backtest.') } }
  return <div className="space-y-8"><div><p className="text-sm font-medium text-slate-500">Simulation</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Backtests</h1><p className="mt-2 text-slate-600">Binance candles are fetched on demand and are not permanently stored.</p></div><form onSubmit={submit} className="grid gap-4 rounded-lg border border-slate-200 bg-white p-5 md:grid-cols-4"><Select label="Symbol" value={symbol} onChange={setSymbol} options={symbols.map(s => s.symbol)} /><Select label="Timeframe" value={interval} onChange={setInterval} options={intervals} /><label className="text-sm font-medium">Start Date<input type="date" value={start} onChange={e => setStart(e.target.value)} className="mt-2 block w-full rounded border border-slate-300 p-2" required /></label><label className="text-sm font-medium">End Date<input type="date" value={end} onChange={e => setEnd(e.target.value)} className="mt-2 block w-full rounded border border-slate-300 p-2" required /></label><button disabled={busy} className="rounded bg-slate-950 px-4 py-2 text-sm font-medium text-white disabled:opacity-50 md:col-span-4">{busy ? 'Running backtest…' : 'Run Backtest'}</button></form>{error && <p className="text-sm text-red-700">{error}</p>}{selected && <Result run={selected} />}<section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Recent Backtests</h2><table className="mt-4 w-full text-left text-sm"><thead className="text-slate-500"><tr><th>Symbol</th><th>Interval</th><th>Trades</th><th>Win rate</th><th>Net PnL</th><th /></tr></thead><tbody>{runs.map(run => <tr key={run.id} className="border-t"><td className="py-3">{run.symbol}</td><td>{run.interval}</td><td>{run.totalTrades}</td><td>{run.winRatePercent.toFixed(1)}%</td><td>{run.netPnlUsdt.toFixed(2)}</td><td><button onClick={() => void open(run.id)} className="text-slate-700">View</button></td></tr>)}</tbody></table></section></div>
}
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="text-sm font-medium">{label}<select value={value} onChange={e => onChange(e.target.value)} className="mt-2 block w-full rounded border border-slate-300 p-2" required><option value="">Select</option>{options.map(option => <option key={option}>{option}</option>)}</select></label> }
function Result({ run }: { run: BacktestRun }) { return <section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">{run.symbol} · {run.interval}</h2><div className="mt-4 grid grid-cols-2 gap-4 text-sm md:grid-cols-5"><Metric label="Candles" value={run.candleCount}/><Metric label="Trades" value={run.totalTrades}/><Metric label="Win rate" value={`${run.winRatePercent.toFixed(1)}%`}/><Metric label="Net PnL" value={run.netPnlUsdt.toFixed(2)}/><Metric label="Fees" value={run.totalFeesUsdt.toFixed(2)}/><Metric label="Profit factor" value={run.profitFactor?.toFixed(2) ?? '—'}/><Metric label="Average R" value={run.averageRMultiple.toFixed(2)}/><Metric label="Max drawdown" value={run.maxDrawdownUsdt.toFixed(2)}/><Metric label="R:R / Fee" value={`${run.riskReward} / ${run.feePercentPerSide}%`}/><Metric label="Order size" value={`${run.fixedOrderSizeUsdt} USDT`}/></div><table className="mt-6 w-full text-left text-xs"><thead className="text-slate-500"><tr><th>#</th><th>Direction</th><th>Entry</th><th>Exit</th><th>Initial SL</th><th>Final TP</th><th>Reason</th><th>Net PnL</th><th>R</th></tr></thead><tbody>{run.trades.map((trade, i) => <tr key={trade.id || i} className="border-t"><td className="py-2">{i + 1}</td><td>{trade.direction}</td><td>{trade.entryPrice}</td><td>{trade.exitPrice}</td><td>{trade.initialStopLoss}</td><td>{trade.finalTakeProfit}</td><td>{trade.exitReason}</td><td>{trade.netPnlUsdt.toFixed(2)}</td><td>{trade.grossRMultiple.toFixed(2)}</td></tr>)}</tbody></table></section> }
function Metric({ label, value }: { label: string; value: string | number }) { return <div><p className="text-slate-500">{label}</p><p className="mt-1 font-medium">{value}</p></div> }
