import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link } from 'react-router-dom'
import type { BacktestRun, BacktestRunSummary, MonitoredSymbol } from '../api'
import { getBacktests, getMonitoredSymbols, runBacktest } from '../api'

const intervals = ['3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h', '12h', '1d', '1w', '1M']
export function BacktestsPage() {
  const [symbols, setSymbols] = useState<MonitoredSymbol[]>([]); const [runs, setRuns] = useState<BacktestRunSummary[]>([]); const [selected, setSelected] = useState<BacktestRun | null>(null); const [symbol, setSymbol] = useState(''); const [interval, setInterval] = useState('30m'); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  async function refresh() { const [saved, history] = await Promise.all([getMonitoredSymbols(), getBacktests()]); setSymbols(saved.filter(item => item.isEnabled && item.source === 'Mt5Exness')); setRuns(history) }
  useEffect(() => { void refresh().catch(error => setError(error instanceof Error ? error.message : 'Could not load backtests.')) }, [])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!symbol || !start || !end || busy) return; setBusy(true); setError(null); try { setSelected(await runBacktest({ symbol, interval, startUtc: `${start}T00:00:00.000Z`, endUtc: `${end}T23:59:59.999Z` })); await refresh() } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Backtest failed.') } finally { setBusy(false) } }
  return <div className="space-y-8"><div><p className="text-sm font-medium text-slate-500">Simulation</p><h1 className="mt-2 text-3xl font-semibold">Backtests</h1><p className="mt-2 text-slate-600">New research uses MT5 / Exness bars. Economics remain the legacy compatibility model until broker-aware sizing and costs are introduced.</p></div><form onSubmit={submit} className="grid gap-4 rounded-lg border border-slate-200 bg-white p-5 md:grid-cols-4"><Select label="Symbol" value={symbol} onChange={setSymbol} options={symbols.map(item => item.displayName ? `${item.symbol} — ${item.displayName}` : item.symbol)} values={symbols.map(item => item.symbol)}/><Select label="Timeframe" value={interval} onChange={setInterval} options={intervals}/><label className="text-sm font-medium">Start date<input className="mt-2 block w-full rounded border border-slate-300 p-2" type="date" value={start} onChange={event => setStart(event.target.value)} required/></label><label className="text-sm font-medium">End date<input className="mt-2 block w-full rounded border border-slate-300 p-2" type="date" value={end} onChange={event => setEnd(event.target.value)} required/></label><button disabled={busy} className="rounded bg-slate-950 px-4 py-2 text-sm font-medium text-white disabled:opacity-50 md:col-span-4">{busy ? 'Running backtest...' : 'Run Backtest'}</button></form>{error && <p className="text-sm text-red-700">{error}</p>}{selected && <Result run={selected}/>}<section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Recent Backtests</h2><table className="mt-4 w-full text-left text-sm"><thead className="text-slate-500"><tr><th>Symbol</th><th>Data</th><th>Interval</th><th>Trades</th><th>Net PnL</th></tr></thead><tbody>{runs.map(run => <tr key={run.id} className="border-t"><td className="py-3">{run.symbol}</td><td>{run.marketDataSourceLabel}</td><td>{run.interval}</td><td>{run.totalTrades}</td><td>{run.netPnlUsdt.toFixed(2)}</td></tr>)}</tbody></table></section></div>
}
function Select({ label, value, onChange, options, values }: { label: string; value: string; onChange: (value: string) => void; options: string[]; values?: string[] }) { return <label className="text-sm font-medium">{label}<select value={value} onChange={event => onChange(event.target.value)} className="mt-2 block w-full rounded border border-slate-300 p-2" required><option value="">Select</option>{options.map((option, index) => <option key={values?.[index] ?? option} value={values?.[index] ?? option}>{option}</option>)}</select></label> }
function Result({ run }: { run: BacktestRun }) { return <section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">{run.symbol} · {run.interval}</h2><p className="mt-2 text-sm text-amber-800">Market data: {run.marketDataSourceLabel} · Economics: Legacy compatibility model</p><p className="mt-2 text-sm text-slate-600">Frozen settings: Adaptive initial SL {run.useAdaptiveInitialStop ? 'On' : 'Off'} · Same-trend re-entry {run.sameTrendReentryEnabled ? 'On' : 'Off'} · Maximum re-entry age {run.maxReentryAgeBars} bars</p><div className="mt-4 grid grid-cols-2 gap-4 text-sm md:grid-cols-5"><Metric label="Candles" value={run.candleCount}/><Metric label="Trades" value={run.totalTrades}/><Metric label="Net PnL" value={run.netPnlUsdt.toFixed(2)}/><Metric label="Crossovers" value={run.totalCrossovers}/><Metric label="Long / short signals" value={`${run.longSignals} / ${run.shortSignals}`}/><Metric label="EMA100 rejected" value={run.rejectedByEma100}/><Metric label="Confirmation failed" value={run.confirmationFailed}/><Metric label="Invalid SL" value={run.invalidStopLoss}/><Metric label="Skipped while open" value={run.skippedWhilePositionOpen}/><Metric label="No entry candle" value={run.noEntryCandle}/></div><table className="mt-6 w-full text-left text-xs"><thead className="text-slate-500"><tr><th>#</th><th>Direction</th><th>Entry</th><th>Exit</th><th>Reason</th><th>Net PnL</th><th>Analyze</th></tr></thead><tbody>{run.trades.map((trade, index) => <tr key={trade.id || index} className="border-t"><td className="py-2">{index + 1}</td><td>{trade.direction}</td><td>{trade.entryPrice}</td><td>{trade.exitPrice}</td><td>{trade.exitReason}</td><td>{trade.netPnlUsdt.toFixed(2)}</td><td><Link to={`/trades?source=backtest&id=${trade.id}`}>View chart</Link></td></tr>)}</tbody></table></section> }
function Metric({ label, value }: { label: string; value: string | number }) { return <div><p className="text-slate-500">{label}</p><p className="mt-1 font-medium">{value}</p></div> }
