import { useEffect, useState } from 'react'
import { getActivePaperSession, getMarketProviderCapabilities, getPaperSessions, stopPaperSession, type MarketProviderCapabilities, type PaperSession, type PaperSessionSummary, type PaperTrade } from '../api'

const price = (value: number | null | undefined) => value === null || value === undefined ? '-' : value.toFixed(4)
const time = (value: string | null | undefined) => value ? new Date(value).toLocaleString() : '-'

export function PaperTradingPage() {
  const [active, setActive] = useState<PaperSession | null>(null); const [history, setHistory] = useState<PaperSessionSummary[]>([]); const [capabilities, setCapabilities] = useState<MarketProviderCapabilities | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false)
  async function refresh() { const [sessions, providerCapabilities] = await Promise.all([getPaperSessions(), getMarketProviderCapabilities()]); setHistory(sessions); setCapabilities(providerCapabilities); try { setActive(await getActivePaperSession()) } catch { setActive(null) } }
  useEffect(() => { void refresh().catch(e => setError(e instanceof Error ? e.message : 'Could not load paper trading.')) }, [])
  async function stop() { if (!active || busy) return; setBusy(true); setError(null); try { await stopPaperSession(active.id); await refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Could not stop the session.') } finally { setBusy(false) } }
  if (active) return <Active session={active} busy={busy} onStop={stop} error={error} />
  return <div className="space-y-8" aria-busy={busy}><div><p className="text-sm font-medium text-slate-500">Simulation</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Paper Trading</h1><p className="mt-2 text-slate-600">Historical paper records remain available for review.</p></div><section className="rounded-lg border border-amber-200 bg-amber-50 p-6"><h2 className="font-semibold text-amber-950">Live Paper is temporarily unavailable until the MT5 market-data adapter is connected.</h2><p className="mt-2 text-sm text-amber-900">Live market data: {capabilities?.liveBarProviderConfigured ? 'Configured' : capabilities ? 'Not configured' : 'Checking…'}. Starting and resuming Paper sessions remain disabled during this migration.</p></section>{error && <p className="text-sm text-red-700">{error}</p>}<History rows={history}/></div>
}

function Active({ session, busy, onStop, error }: { session: PaperSession; busy: boolean; onStop: () => Promise<void>; error: string | null }) {
  const openTrades = session.symbols.flatMap(symbol => symbol.openTrade ? [{ symbol: symbol.symbol, trade: symbol.openTrade }] : [])
  return <div className="space-y-7" aria-busy={busy}><div><p className="text-sm font-medium text-amber-700">PAPER MODE</p><h1 className="mt-2 text-3xl font-semibold">{session.status} · {session.interval}</h1><p className="mt-2 text-slate-600">Live Paper is temporarily unavailable until the MT5 market-data adapter is connected. Connection: {session.connectionState}</p></div><div className="flex gap-3">{session.status !== 'Interrupted' && <button disabled={busy} onClick={() => void onStop()} className="rounded bg-slate-950 px-4 py-2 text-sm font-medium text-white">{busy ? 'Stopping…' : 'Stop Session'}</button>}</div>{error && <p className="text-sm text-red-700">{error}</p>}<section className="overflow-x-auto rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Session symbols</h2><table className="mt-4 w-full text-left text-sm"><thead className="text-slate-500"><tr><th>Symbol</th><th>Price</th><th>Trend</th><th>EMA9</th><th>EMA15</th><th>EMA100</th><th>Gap state</th><th>Last closed candle</th><th>Pending entry</th><th>Position</th></tr></thead><tbody>{session.symbols.map(symbol => <tr key={symbol.symbol} className="border-t"><td className="py-3">{symbol.symbol}</td><td>{price(symbol.latestPrice)}</td><td>{symbol.trend ?? '-'}</td><td>{price(symbol.ema9)}</td><td>{price(symbol.ema15)}</td><td>{price(symbol.ema100)}</td><td>{symbol.gapState ?? '-'}</td><td>{time(symbol.lastClosedCandleUtc)}</td><td>{symbol.pendingDirection ?? '-'}</td><td>{symbol.openTrade?.direction ?? '-'}</td></tr>)}</tbody></table></section><section className="overflow-x-auto rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Open positions</h2>{openTrades.length === 0 ? <p className="mt-3 text-sm text-slate-500">No open paper positions.</p> : <table className="mt-4 w-full text-left text-sm"><thead className="text-slate-500"><tr><th>Symbol</th><th>Side</th><th>Entry</th><th>Current</th><th>Quantity</th><th>Stop loss</th><th>Take profit</th><th>Best / adverse</th><th>Net P/L</th></tr></thead><tbody>{openTrades.map(({ symbol, trade }) => <PositionRow key={trade.id} symbol={symbol} trade={trade} session={session} />)}</tbody></table>}</section><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Completed trades</h2><div className="mt-3 space-y-2 text-sm">{session.recentTrades.filter(trade => trade.status === 'Closed').map(trade => <p key={trade.id}>{trade.symbol} {trade.direction} · {trade.exitReason} · Net {trade.netPnlUsdt.toFixed(2)} · <a href={`/trades?source=paper&id=${trade.id}`} className="underline">Analyze</a></p>)}</div></section></div>
}

function PositionRow({ symbol, trade, session }: { symbol: string; trade: PaperTrade; session: PaperSession }) {
  const current = session.symbols.find(item => item.symbol === symbol)?.latestPrice
  const gross = current === null || current === undefined ? null : (trade.direction === 'Long' ? (current - trade.entryPrice) : (trade.entryPrice - current)) * trade.quantity
  const fees = current === null || current === undefined ? null : (trade.entryPrice * trade.quantity + current * trade.quantity) * session.feePercentPerSide / 100
  const net = gross === null || fees === null ? null : gross - fees
  return <tr className="border-t"><td className="py-3">{symbol}</td><td>{trade.direction}</td><td>{price(trade.entryPrice)}</td><td>{price(current)}</td><td>{price(trade.quantity)}</td><td>{price(trade.currentStopLoss)}</td><td>{price(trade.currentTakeProfit)}</td><td>{price(trade.mfePrice)} / {price(trade.maePrice)}</td><td>{net === null ? '-' : net.toFixed(2)}</td><td><a href={`/trades?source=paper&id=${trade.id}`} className="underline">Analyze</a></td></tr>
}

function History({ rows }: { rows: PaperSessionSummary[] }) { return <section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-semibold">Paper session history</h2><div className="mt-3 space-y-2 text-sm">{rows.map(row => <p key={row.id}>{new Date(row.startedAtUtc).toLocaleString()} · {row.interval} · {row.symbolCount} symbols · {row.status} · {row.completedTrades} trades · {row.netPnlUsdt.toFixed(2)} net</p>)}</div></section> }
