import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { getTradingSettings, updateTradingSettings, type TradingSettings } from '../api'

export function SettingsPage() {
  const [settings, setSettings] = useState<TradingSettings | null>(null); const [error, setError] = useState<string | null>(null); const [saved, setSaved] = useState(false)
  useEffect(() => { void getTradingSettings().then(setSettings).catch(error => setError(error instanceof Error ? error.message : 'Could not load settings.')) }, [])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!settings) return; setError(null); setSaved(false); try { setSettings(await updateTradingSettings({ riskReward: settings.riskReward, fixedOrderSizeUsdt: settings.fixedOrderSizeUsdt, waitForConfirmationCandle: settings.waitForConfirmationCandle, useEma100Filter: settings.useEma100Filter, trailingStopEnabled: settings.trailingStopEnabled, feePercentPerSide: settings.feePercentPerSide })); setSaved(true) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Could not save settings.') } }
  if (!settings) return <p className="text-sm text-slate-500">Loading settings…</p>
  return <div><p className="text-sm font-medium text-slate-500">Configuration</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Trading Settings</h1><form onSubmit={submit} className="mt-8 max-w-2xl space-y-7 rounded-lg border border-slate-200 bg-white p-6"><label className="block text-sm font-medium">Risk / Reward<input type="number" min="0.1" step="0.1" value={settings.riskReward} onChange={event => setSettings({ ...settings, riskReward: Number(event.target.value) })} className="mt-2 block w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">Fixed Order Size (USDT)<input type="number" min="1" step="1" value={settings.fixedOrderSizeUsdt} onChange={event => setSettings({ ...settings, fixedOrderSizeUsdt: Number(event.target.value) })} className="mt-2 block w-full rounded-md border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">Trading Fee Per Side (%)<input type="number" min="0" max="5" step="0.01" value={settings.feePercentPerSide} onChange={event => setSettings({ ...settings, feePercentPerSide: Number(event.target.value) })} className="mt-2 block w-full rounded-md border border-slate-300 px-3 py-2" /><span className="mt-1 block text-sm font-normal text-slate-500">Simulation fee applied separately to entry and exit. Actual Binance Futures fees may vary by account tier, order type, discounts, and promotions.</span></label><Check label="Wait for Confirmation Candle" help="When enabled, the bot waits for the candle after the EMA crossover candle to close before confirming an entry." checked={settings.waitForConfirmationCandle} onChange={value => setSettings({ ...settings, waitForConfirmationCandle: value })}/><Check label="Use EMA 100 Direction Filter" help="When enabled, long entries require EMA 9 and EMA 15 above EMA 100. Short entries require both below EMA 100." checked={settings.useEma100Filter} onChange={value => setSettings({ ...settings, useEma100Filter: value })}/><Check label="Enable Trailing Stop" help="When enabled, profitable trades will later use the configured EMA-Bot trailing-stop rules." checked={settings.trailingStopEnabled} onChange={value => setSettings({ ...settings, trailingStopEnabled: value })}/>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}{saved && <p className="text-sm text-emerald-700">Settings saved.</p>}<button className="rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white">Save settings</button></form></div>
}
function Check({ label, help, checked, onChange }: { label: string; help: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex gap-3"><input type="checkbox" checked={checked} onChange={event => onChange(event.target.checked)} className="mt-1"/><span><span className="block text-sm font-medium">{label}</span><span className="mt-1 block text-sm leading-6 text-slate-500">{help}</span></span></label> }
