import { useEffect, useState } from 'react'
import { addMonitoredSymbol, getInstruments, getMarketProviderCapabilities, getMonitoredSymbols, removeMonitoredSymbol, setPaperCommission, setSymbolEnabled, type InstrumentCatalogItem, type MarketProviderCapabilities, type MonitoredSymbol } from '../api'

export function SymbolsPage() {
  const [monitored, setMonitored] = useState<MonitoredSymbol[]>([]); const [catalog, setCatalog] = useState<InstrumentCatalogItem[]>([]); const [capabilities, setCapabilities] = useState<MarketProviderCapabilities | null>(null); const [error, setError] = useState<string | null>(null)
  async function refresh() { setError(null); try { const [symbols, caps] = await Promise.all([getMonitoredSymbols(), getMarketProviderCapabilities()]); setMonitored(symbols); setCapabilities(caps); setCatalog(caps.instrumentCatalogConfigured ? await getInstruments() : []) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load MT5 instruments.') } }
  useEffect(() => { void refresh() }, [])
  async function setCommission(symbol: MonitoredSymbol) { const raw = window.prompt(`Paper commission per lot per side for ${symbol.symbol}. Use 0 only if confirmed commission-free.`, symbol.paperCommissionPerLotPerSide?.toString() ?? ''); if (raw === null || raw.trim() === '') return; const value = Number(raw); if (!Number.isFinite(value) || value < 0) { setError('Commission must be zero or greater.'); return } try { await setPaperCommission(symbol.id, value); await refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save Paper commission.') } }
  return <div className="space-y-8"><div><p className="text-sm font-medium text-slate-500">Market data</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Symbols</h1><p className="mt-3 text-slate-600">Exact MT5/Exness Market Watch symbols are used for active research and broker-aware Paper.</p></div><p className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">Enter the commission shown for this Exness account/instrument. Use 0 only when the account/instrument is confirmed commission-free.</p>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<section className="rounded-lg border bg-white p-5"><div className="flex justify-between"><div><h2 className="font-semibold">MT5 Market Watch catalog</h2><p className="text-sm text-slate-500">{capabilities?.instrumentCatalogConfigured ? 'Configured' : 'Not configured'}</p></div><button onClick={() => void refresh()} className="rounded border px-3 py-2 text-sm">Refresh</button></div><table className="mt-4 w-full text-left text-sm"><thead><tr><th>Broker symbol</th><th>Description</th><th /></tr></thead><tbody>{catalog.filter(item => item.isSelected).map(item => <tr key={item.spec.brokerSymbol} className="border-t"><td className="py-3 font-medium">{item.spec.brokerSymbol}</td><td>{item.description ?? item.spec.displaySymbol ?? '—'}</td><td className="text-right">{monitored.some(symbol => symbol.symbol === item.spec.brokerSymbol && symbol.source === 'Mt5Exness') ? 'Monitored' : <button onClick={() => void addMonitoredSymbol(item.spec.brokerSymbol).then(refresh).catch(e => setError(e.message))}>Add</button>}</td></tr>)}</tbody></table></section><section className="rounded-lg border bg-white p-5"><h2 className="font-semibold">Monitored instruments</h2><table className="mt-4 w-full text-left text-sm"><thead><tr><th>Source</th><th>Symbol</th><th>Paper commission / lot / side</th><th>Status</th><th /></tr></thead><tbody>{monitored.map(symbol => <tr key={symbol.id} className="border-t"><td className="py-3">{symbol.sourceLabel}</td><td className="font-medium">{symbol.symbol}</td><td>{symbol.paperCommissionPerLotPerSide === null ? 'Not configured' : symbol.paperCommissionPerLotPerSide === 0 ? 'Commission-free (0)' : symbol.paperCommissionPerLotPerSide}</td><td>{symbol.isEnabled ? 'Enabled' : 'Disabled'}</td><td className="space-x-3 text-right">{symbol.source === 'Mt5Exness' && <button onClick={() => void setCommission(symbol)}>Set Paper cost</button>}<button onClick={() => void setSymbolEnabled(symbol.id, !symbol.isEnabled).then(refresh).catch(e => setError(e.message))}>{symbol.isEnabled ? 'Disable' : 'Enable'}</button><button className="text-red-700" onClick={() => void removeMonitoredSymbol(symbol.id).then(refresh).catch(e => setError(e.message))}>Remove</button></td></tr>)}</tbody></table></section></div>
}
