export type CurrentUser = {
  userName: string
  email: string
  role: string
}

export type HealthStatus = {
  api: string
  database: string
}

export type MarketProviderCapabilities = { historicalProvider: string; historicalResearchConfigured: boolean; targetTerminal: string; targetBroker: string; instrumentCatalogConfigured: boolean; quoteProviderConfigured: boolean; liveBarProviderConfigured: boolean; executionProviderConfigured: boolean; nativeTargetTimeframes: string[] }
export type Mt5BridgeStatus = { enabled: boolean; protocolVersion: number; pipeName: string; connectionState: 'Disabled' | 'WaitingForClient' | 'Handshaking' | 'Connected' | 'Stale' | 'Faulted'; sessionId: string | null; connectedAtUtc: string | null; lastMessageAtUtc: string | null; lastHeartbeatAtUtc: string | null; lastDisconnectAtUtc: string | null; lastDisconnectReason: string | null; clientVersion: string | null; terminalName: string | null; terminalCompany: string | null; terminalBuild: number | null; accountServer: string | null; accountCurrency: string | null; accountMode: string | null; lastRoundTripMs: number | null }

export type MonitoredSymbol = { id: number; source: 'LegacyBinance' | 'Mt5Exness'; sourceLabel: string; symbol: string; displayName: string | null; baseAsset: string | null; quoteAsset: string | null; isEnabled: boolean; paperCommissionPerLotPerSide: number | null }
export type InstrumentCatalogItem = { spec: { brokerSymbol: string; displaySymbol: string | null; currencyBase: string | null; currencyProfit: string | null; volumeMin: number; volumeMax: number; volumeStep: number }; description: string | null; isSelected: boolean; isVisible: boolean }
export type PositionSizingMode = 'FixedNotional' | 'MarginPercent'
export type PaperPositionSizingMode = 'FixedLots' | 'MarginPercent'
export type TradingSettings = { riskReward: number; fixedOrderSizeUsdt: number; minEmaGapPercent: number; maxStopDistancePercent: number; positionSizingMode: PositionSizingMode; simulatedAccountBalanceUsdt: number; marginPerTradePercent: number; leverage: number; waitForConfirmationCandle: boolean; useEma100Filter: boolean; useHtfRegimeFilter: boolean; trailingStopEnabled: boolean; useAdaptiveInitialStop: boolean; sameTrendReentryEnabled: boolean; maxReentryAgeBars: number; exitOnOppositeCrossover: boolean; feePercentPerSide: number; paperPositionSizingMode: PaperPositionSizingMode; paperFixedLots: number; paperMarginPerTradePercent: number; paperStartingBalance: number; updatedAtUtc: string }
export type BacktestRunSummary = { id: number; symbol: string; marketDataSource: 'LegacyBinance' | 'Mt5Exness'; marketDataSourceLabel: string; interval: string; requestedStartUtc: string; requestedEndUtc: string; actualStartUtc: string | null; actualEndUtc: string | null; createdAtUtc: string; completedAtUtc: string | null; candleCount: number; totalTrades: number; winningTrades: number; losingTrades: number; breakEvenTrades: number; longTrades: number; shortTrades: number; winRatePercent: number; grossPnlUsdt: number; netPnlUsdt: number; totalFeesUsdt: number; profitFactor: number | null; averageNetPnlUsdt: number; averageRMultiple: number; maxDrawdownUsdt: number; totalCrossovers: number; longSignals: number; shortSignals: number; rejectedByEma100: number; rejectedByHtfRegime: number; confirmationFailed: number; invalidStopLoss: number; skippedWhilePositionOpen: number; noEntryCandle: number; riskReward: number; fixedOrderSizeUsdt: number; waitForConfirmationCandle: boolean; useEma100Filter: boolean; useHtfRegimeFilter: boolean; trailingStopEnabled: boolean; useAdaptiveInitialStop: boolean; sameTrendReentryEnabled: boolean; maxReentryAgeBars: number; exitOnOppositeCrossover: boolean; feePercentPerSide: number; status: string; failureMessage: string | null; economicsMode?: 'LegacyCompatibility' | 'Mt5HistoricalBidAsk' | null; accountCurrency?: string | null; brokerSymbol?: string | null; historicalSpreadModel?: string | null; historicalChartMode?: string | null; commissionPerLotPerSide?: number | null; startingBalance?: number | null; endingBalance?: number | null; grossProfitFactor?: number | null; netProfitFactor?: number | null; rejectedByTradingCosts?: number; mt5EconomicsCallCount?: number; mt5EconomicsElapsedMilliseconds?: number; rejectedByInsufficientMargin?: number; rejectedByInvalidVolume?: number; rejectedByTradeMode?: number }
export type BacktestRun = BacktestRunSummary & { trades: BacktestTrade[] }
export type Mt5HistoricalBacktestEconomicsPreview = { ready: boolean; reason: string | null; brokerSymbol: string | null; accountCurrency: string | null; startingBalance: number | null; sizingMode: 'FixedLots' | 'MarginPercent' | null; fixedLots: number | null; marginPerTradePercent: number | null; commissionPerLotPerSide: number | null; historicalSpreadModel: string | null; chartMode: string | null; contractSize: number | null; volumeMin: number | null; volumeMax: number | null; volumeStep: number | null; volumeLimit: number | null; stopsLevelPoints: number | null; tradeMode: string | null; pointSize: number | null }
export type BacktestTrade = { id: number; direction: string; entryTimeUtc: string; exitTimeUtc: string; entryPrice: number; exitPrice: number; initialStopLoss: number; finalStopLoss: number; originalTakeProfit: number; finalTakeProfit: number; exitReason: string; netPnlUsdt: number; netPnlPercent: number; grossRMultiple: number }
export type PaperDecision = { id: number | null; timeUtc: string; candleCloseTimeUtc: string | null; stage: string; direction: string | null; message: string; ema9: number | null; ema15: number | null; ema100: number | null; gapPercent: number | null; gapState: string | null; stopPrice: number | null; stopSource: string | null; expectedEntryOpenUtc: string | null; bid: number | null; ask: number | null; entryPrice: number | null; lots: number | null; requiredMargin: number | null }
export type PaperPendingEntry = { direction: string; crossoverTimeUtc: string; signalTimeUtc: string; expectedEntryOpenUtc: string; stopPrice: number; stopSource: string; stopSourceTimeUtc: string; signalOpen: number | null; signalClose: number; signalEma9: number | null; signalEma15: number | null; signalEma100: number | null; signalGapPercent: number | null; signalGapState: string; isReentry: boolean }
export type PaperTrade = { id: number; symbol: string; status: string; direction: string; crossoverTimeUtc: string; signalTimeUtc: string; entryTimeUtc: string; exitTimeUtc: string | null; entryPrice: number; exitPrice: number | null; quantity: number; initialStopLoss: number; currentStopLoss: number; finalStopLoss: number | null; stopSourceType: string; stopSourceTimeUtc: string; originalTakeProfit: number; currentTakeProfit: number; finalTakeProfit: number | null; takeProfitExtended: boolean; bestFavorableProgressPercent: number; grossPnlUsdt: number; netPnlUsdt: number; netPnlPercent: number; mfePrice: number; mfePercent: number | null; maePrice: number; maePercent: number | null; exitReason: string | null; lots: number | null; entryBid: number | null; entryAsk: number | null; entrySpread: number | null; spreadToInitialRiskPercent: number | null; exitBid: number | null; exitAsk: number | null; exitSpread: number | null; requiredMargin: number | null; marginUsed: number | null; accountEquityAtEntry: number | null; roundTripCommission: number | null; grossPnl: number | null; netPnl: number | null; signalOpen: number | null; signalClose: number; signalEma9: number | null; signalEma15: number | null; signalEma100: number | null; signalGapPercent: number | null; signalGapState: string; isReentry: boolean; trendRegimeCrossoverTimeUtc: string | null; reentryAgeBars: number | null; currentGrossPnl: number | null; currentNetPnl: number | null; currentPnlPercent: number | null; currentPnlCalculatedAtUtc: string | null; currentPnlAvailable: boolean; useAdaptiveInitialStop: boolean; signalAtr14: number | null; reversalPowerScore: number | null; reversalPowerBand: string | null; stopAnchorPrice: number | null; stopBuffer: number | null; pnlPercentOnMargin: number | null; accountReturnPercent: number | null; initialRiskAmount: number | null }
export type PaperRuntimeCandle = { openTimeUtc: string; closeTimeUtc: string; open: number; high: number; low: number; close: number }
export type PaperSymbol = { symbol: string; latestPrice: number | null; latestBid: number | null; latestAsk: number | null; latestSpread: number | null; lastMarketEventUtc: string | null; lastClosedCandleUtc: string | null; formingCandle: PaperRuntimeCandle | null; lastEvaluatedCandleUtc: string | null; trend: string | null; ema9: number | null; ema15: number | null; ema100: number | null; gapPercent: number | null; gapState: string | null; pendingDirection: string | null; pendingEntry: PaperPendingEntry | null; trendRegimeDirection: string | null; trendRegimeCrossoverTimeUtc: string | null; reentryEligible: boolean; reentryConsumed: boolean; currentExecutableExitPrice: number | null; lastDecision: PaperDecision | null; recentDecisions: PaperDecision[]; runtimeDecisionHistoryAvailable: boolean; openTrade: PaperTrade | null }
export type PaperSession = { id: number; interval: string; status: string; startedAtUtc: string; stoppedAtUtc: string | null; interruptedAtUtc: string | null; failureMessage: string | null; riskReward: number; fixedOrderSizeUsdt: number; minEmaGapPercent: number; maxStopDistancePercent: number; waitForConfirmationCandle: boolean; useEma100Filter: boolean; trailingStopEnabled: boolean; useAdaptiveInitialStop: boolean; sameTrendReentryEnabled: boolean; maxReentryAgeBars: number; exitOnOppositeCrossover: boolean; feePercentPerSide: number; totalCrossovers: number; longSignals: number; shortSignals: number; rejectedByEma100: number; rejectedByEmaGap: number; rejectedByStopDistance: number; rejectedByFees: number; rejectedByTradingCosts: number; rejectedByInsufficientMargin: number; rejectedByInvalidVolume: number; rejectedByExecutableStop: number; confirmationFailed: number; invalidStopLoss: number; skippedWhilePositionOpen: number; completedTrades: number; netPnlUsdt: number; totalFeesUsdt: number; connectionState: string; lastUpdateUtc: string | null; symbols: PaperSymbol[]; recentTrades: PaperTrade[]; marketDataSource: string; accountCurrency: string; paperPositionSizingMode: PaperPositionSizingMode; paperFixedLots: number; paperMarginPerTradePercent: number; startingBalance: number; currentBalance: number; usedMargin: number; netPnl: number; totalTradingCosts: number; balanceReconciliationOk: boolean; balanceReconciliationDifference: number; marginReconciliationOk: boolean; marginReconciliationDifference: number; wasInterrupted: boolean; interruptionCount: number; interruptionDuration: string }
export type PaperSessionSummary = { id: number; interval: string; status: string; startedAtUtc: string; stoppedAtUtc: string | null; interruptedAtUtc: string | null; symbolCount: number; completedTrades: number; netPnlUsdt: number; totalFeesUsdt: number; accountCurrency: string; netPnl: number; totalTradingCosts: number; failureMessage: string | null; openTradeCount: number }
export type TradeSource = 'Backtest' | 'Paper' | 'ExnessDemo'
export type TradeSummary = { source: TradeSource; id: number; parentId: number; symbol: string; interval: string; status: string; direction: string; entryTimeUtc: string; exitTimeUtc: string | null; entryPrice: number | null; exitPrice: number | null; exitReason: string | null; grossPnlUsdt: number | null; netPnlUsdt: number | null; netPnlPercent: number | null; totalFeesUsdt: number | null; grossRMultiple: number | null; netRMultiple: number | null; marketDataSource: 'LegacyBinance' | 'Mt5Exness'; accountCurrency: string; grossPnl: number | null; netPnl: number | null; tradingCosts: number | null; pnlPercentBasis: string; pnlPercentOnMargin: number | null; accountReturnPercent: number | null; sessionId?: number | null; intentId?: number | null; isReentry?: boolean | null; crossoverTimeUtc?: string | null; signalTimeUtc?: string | null; expectedEntryOpenUtc?: string | null; brokerExecutedAtUtc?: string | null; averageFillPrice?: number | null; filledVolumeLots?: number | null; brokerClosedAtUtc?: string | null; averageClosePrice?: number | null; nativeExitReason?: string | null; pnlEvidenceAvailable?: boolean; pnlEvidenceType?: string | null; pnlEvidenceReason?: string | null; reconciliationSource?: string | null; reconciliationNote?: string | null }
export type TradeManagementEvent = { timeUtc: string; effectiveTimeUtc: string | null; type: string; marketPrice: number; oldStop: number | null; newStop: number | null; oldTakeProfit: number | null; newTakeProfit: number | null; progressPercent: number | null }
export type TradeDetail = { summary: TradeSummary; crossoverTimeUtc: string; signalTimeUtc: string; quantity: number; entryNotionalUsdt: number; initialStopLoss: number; finalStopLoss: number; stopSourceType: string; stopSourceTimeUtc: string; originalTakeProfit: number; finalTakeProfit: number; takeProfitExtended: boolean; entryFeeUsdt: number; exitFeeUsdt: number | null; mfePrice: number; mfePercent: number; maePrice: number; maePercent: number; signalOpen: number | null; signalClose: number; signalEma9: number | null; signalEma15: number | null; signalEma100: number | null; signalGapPercent: number | null; signalGapState: string; riskReward: number; fixedOrderSizeUsdt: number; waitForConfirmationCandle: boolean; useEma100Filter: boolean; trailingStopEnabled: boolean; feePercentPerSide: number; positionSizingMode: PositionSizingMode; accountEquityAtEntryUsdt: number | null; marginUsedUsdt: number | null; leverage: number | null; isReentry: boolean; trendRegimeCrossoverTimeUtc: string | null; minEmaGapPercent: number; events: TradeManagementEvent[]; hasDetailedManagementHistory: boolean; lots: number | null; requiredMargin: number | null; marginUsed: number | null; accountEquityAtEntry: number | null; roundTripCommission: number | null; entryBid: number | null; entryAsk: number | null; entrySpread: number | null; exitBid: number | null; exitAsk: number | null; exitSpread: number | null; paperPositionSizingMode: PaperPositionSizingMode | null; useAdaptiveInitialStop: boolean; signalAtr14: number | null; reversalPowerScore: number | null; reversalPowerBand: string | null; stopAnchorPrice: number | null; stopBuffer: number | null; initialRiskAmount: number | null }
export type ExnessDemoTradeSummary = { source: 'ExnessDemo'; id: number; parentId: number; sessionId: number; intentId: number; symbol: string; interval: string; direction: string; isReentry: boolean; status: string; crossoverTimeUtc: string; signalTimeUtc: string; expectedEntryOpenUtc: string; brokerExecutedAtUtc: string | null; averageFillPrice: number | null; filledVolumeLots: number | null; brokerClosedAtUtc: string | null; averageClosePrice: number | null; nativeExitReason: string | null; accountCurrency: string | null; evaluatedBrokerPnl: number | null; pnlEvidenceType: string | null; pnlEvidenceAvailable: boolean; pnlEvidenceReason: string | null; reconciliationSource: string | null; reconciliationNote: string | null }
export type ExnessDemoTradeIntent = { sessionId: number; intentId: number; executionId: number; clientExecutionId: string; entryType: string; direction: string; status: string; reason: string | null; crossoverTimeUtc: string; signalTimeUtc: string; expectedEntryOpenUtc: string; signalOpen: number; signalClose: number; signalEma9: number | null; signalEma15: number | null; signalEma100: number | null; signalGapPercent: number | null; signalGapState: string; structuralStopLoss: number; stopSourceType: string; stopSourceTimeUtc: string; intendedTakeProfit: number | null; intendedVolumeLots: number; isReentry: boolean; reentrySourceDemoExecutionId: number | null; trendRegimeCrossoverTimeUtc: string | null; reentryAgeBars: number | null }
export type ExnessDemoTradeSessionSnapshot = { initialAllocation: number; automationEnabledAtCreation: boolean; fixedLots: number; riskReward: number; waitForConfirmationCandle: boolean; useEma100Filter: boolean; minEmaGapPercent: number; maxStopDistancePercent: number; useAdaptiveInitialStop: boolean; trailingStopEnabled: boolean; exitOnOppositeCrossover: boolean; sameTrendReentryEnabled: boolean; maxReentryAgeBars: number }
export type ExnessDemoTradeExecution = { state: string; provider: string; brokerSymbol: string; side: string; volumeLots: number; filledVolumeLots: number | null; averageFillPrice: number | null; closedVolumeLots: number | null; averageClosePrice: number | null; requestedStopLoss: number | null; requestedTakeProfit: number | null; currentStopLoss: number | null; currentTakeProfit: number | null; protectionObservedAtUtc: string | null; magicNumber: number; positionTicket: number | null; positionIdentifier: number | null; orderTicket: number | null; entryDealTicket: number | null; exitDealTicket: number | null; nativeExitReason: string | null; nativeExitReasonConflicted: boolean; brokerRetcode: string | null; brokerMessage: string | null; createdAtUtc: string; preflightAtUtc: string | null; submittedAtUtc: string | null; brokerAcceptedAtUtc: string | null; brokerExecutedAtUtc: string | null; brokerClosedAtUtc: string | null; closedAtUtc: string | null; reconciledAtUtc: string | null; reconciliationSource: string | null; reconciliationNote: string | null }
export type ExnessDemoTradePnl = { brokerAccountCurrency: string | null; brokerEntryProfit: number | null; brokerEntryCommission: number | null; brokerEntrySwap: number | null; brokerEntryFee: number | null; brokerEntryPnlObservedAtUtc: string | null; brokerCurrentProfit: number | null; brokerCurrentSwap: number | null; brokerCurrentPnlObservedAtUtc: string | null; brokerHistoryProfit: number | null; brokerHistoryCommission: number | null; brokerHistorySwap: number | null; brokerHistoryFee: number | null; brokerHistoryPnlObservedAtUtc: string | null; evaluatedAvailable: boolean; evaluatedAmount: number | null; evaluatedEvidenceType: string | null; evaluatedReason: string }
export type ExnessDemoTradeDetail = { summary: ExnessDemoTradeSummary; intent: ExnessDemoTradeIntent; session: ExnessDemoTradeSessionSnapshot; execution: ExnessDemoTradeExecution; brokerPnl: ExnessDemoTradePnl; management: DemoStrategyManagement[]; managementActions: DemoExecutionManagementAction[] }
export type TradeChartCandle = { openTimeUtc: string; closeTimeUtc: string; open: number; high: number; low: number; close: number; volume: number }
export type TradeChartPoint = { timeUtc: string; value: number | null }
export type TradeChartData = { symbol: string; interval: string; candles: TradeChartCandle[]; ema9: TradeChartPoint[]; ema15: TradeChartPoint[]; ema100: TradeChartPoint[] }
export type OptimizerGrid = { riskRewards: number[]; minEmaGapPercents: number[]; maxStopDistancePercents: number[]; waitForConfirmationCandles: boolean[]; useEma100Filters: boolean[]; trailingStopEnableds: boolean[] }
export type OptimizerOptions = { enabledSymbols: string[]; supportedTimeframes: string[]; assumptions: TradingSettings; defaultGrid: OptimizerGrid }
export type OptimizerRun = { id: number; marketDataSource: 'LegacyBinance' | 'Mt5Exness'; marketDataSourceLabel: string; status: string; phase: string; finalizationTotalMarkets: number | null; finalizationCompletedMarkets: number | null; createdAtUtc: string; startedAtUtc: string | null; completedAtUtc: string | null; failureMessage: string | null; requestedStartUtc: string; requestedEndUtc: string; candidateCount: number; marketCount: number; totalWork: number; completedWork: number; progress: number; recommendedCandidateId: number | null; robustCandidateCount: number; assumptions: { simulatedAccountBalanceUsdt: number; fixedOrderSizeUsdt: number; marginPerTradePercent: number; leverage: number; feePercentPerSide: number; positionSizingMode: string } }
export type OptimizerCandidate = { id: number; riskReward: number; minEmaGapPercent: number; maxStopDistancePercent: number; waitForConfirmationCandle: boolean; useEma100Filter: boolean; trailingStopEnabled: boolean; isBaseline: boolean; robustCandidate: boolean; robustRank: number | null; profitableMarketRatio: number; validation: { totalTrades: number; winRatePercent: number; netPnlUsdt: number; netProfitFactor: number | null; netReturnPercent: number; maxDrawdownPercent: number; medianExpectedNetTargetR: number } }

type AntiforgeryResponse = { token: string }
type ApiMessage = { message?: string }

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, { credentials: 'include', ...init })
  if (!response.ok) {
    const body = (await response.json().catch(() => ({}))) as ApiMessage
    throw new ApiError(response.status, body.message ?? 'The request could not be completed.')
  }
  return response.status === 204 ? (undefined as T) : (response.json() as Promise<T>)
}

export class ApiError extends Error {
  constructor(public readonly status: number, message: string) {
    super(message)
  }
}

async function antiforgeryToken(signal?: AbortSignal): Promise<string> {
  const response = await request<AntiforgeryResponse>('/api/auth/antiforgery', { signal })
  return response.token
}

export async function getCurrentUser(): Promise<CurrentUser> {
  return request<CurrentUser>('/api/auth/me')
}

export async function login(userName: string, password: string): Promise<void> {
  const token = await antiforgeryToken()
  await request<void>('/api/auth/login', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': token },
    body: JSON.stringify({ userName, password }),
  })
}

export async function logout(): Promise<void> {
  const token = await antiforgeryToken()
  await request<void>('/api/auth/logout', {
    method: 'POST',
    headers: { 'X-CSRF-TOKEN': token },
  })
}

export async function getHealth(): Promise<HealthStatus> {
  return request<HealthStatus>('/api/health')
}

export const getMarketProviderCapabilities = () => request<MarketProviderCapabilities>('/api/market/provider-capabilities')
export const getMt5BridgeStatus = () => request<Mt5BridgeStatus>('/api/mt5/bridge/status')
export type DemoAutomationSafety = { marketDataBridgeEnabled: boolean; marketDataConnectionState: string; executionBridgeEnabled: boolean; executionReady: boolean; executionReason: string; accountMode: string | null; accountTradeAllowed: boolean | null; expertTradeAllowed: boolean | null; dotNetDemoExecutionEnabled: boolean; demoOnlyLockEnabled: boolean; eaDemoExecutionEnabled: boolean | null; eaDemoExecutionAllowed: boolean | null; eaBuildId?: string | null; supportsExactProtectionReadback?: boolean | null; supportsNativeExitReason?: boolean | null; supportsBrokerPnlEvidence?: boolean | null; automationEnabled: boolean; managementEnabled: boolean; fixedLots: number }
export type DemoExecutionManagementAction = { id: number; clientManagementActionId: string; kind: string; state: string; requestedStopLoss: number | null; requestedTakeProfit: number | null; observedBeforeStopLoss: number | null; observedBeforeTakeProfit: number | null; appliedStopLoss: number | null; appliedTakeProfit: number | null; brokerRetcode: string | null; brokerMessage: string | null; createdAtUtc: string; submittedAtUtc: string | null; completedAtUtc: string | null; reconciledAtUtc: string | null; reconciliationNote: string | null; reconciliationSource: string | null }
export type DemoExecutionSummary = { id: number; clientExecutionId: string; state: string; provider: string; brokerSymbol: string; side: string; volumeLots: number; requestedStopLoss: number | null; requestedTakeProfit: number | null; currentStopLoss: number | null; currentTakeProfit: number | null; protectionObservedAtUtc: string | null; magicNumber: number; positionTicket: number | null; positionIdentifier: number | null; orderTicket: number | null; entryDealTicket: number | null; exitDealTicket: number | null; nativeExitReason: string | null; nativeExitReasonConflicted: boolean; filledVolumeLots: number | null; averageFillPrice: number | null; closedVolumeLots: number | null; averageClosePrice: number | null; brokerExecutedAtUtc: string | null; brokerClosedAtUtc: string | null; brokerRetcode: string | null; brokerMessage: string | null; createdAtUtc: string; preflightAtUtc: string | null; submittedAtUtc: string | null; brokerAcceptedAtUtc: string | null; closedAtUtc: string | null; reconciledAtUtc: string | null; reconciliationNote: string | null; reconciliationSource: string | null; managementActions: DemoExecutionManagementAction[] }
export type DemoStrategyIntent = { id: number; direction: string; crossoverTimeUtc: string; signalTimeUtc: string; expectedEntryOpenUtc: string; structuralStopLoss: number; intendedTakeProfit: number | null; intendedVolumeLots: number; clientExecutionId: string; status: string; demoExecutionId: number | null; isReentry: boolean; reentrySourceDemoExecutionId: number | null; trendRegimeCrossoverTimeUtc: string | null; reentryAgeBars: number | null; reason: string | null; execution: DemoExecutionSummary | null }
export type DemoStrategyManagement = { id: number; demoStrategyIntentId: number; demoExecutionId: number; state: string; originalEntryPrice: number; originalStopLoss: number; originalTakeProfit: number; bestFavorablePrice: number | null; bestFavorableProgressPercent: number; takeProfitExtensionState: string; targetExtensionAppliedAtUtc: string | null; highestAttemptedLockPercent: number; highestAppliedLockPercent: number; pendingProtectionActionId: string | null; pendingProtectionLockPercent: number | null; pendingProtectionExtendsTarget: boolean; pendingDesiredStopLoss: number | null; pendingDesiredTakeProfit: number | null; oppositeSignalTimeUtc: string | null; oppositeSignalDirection: string | null; oppositeCloseState: string; oppositeCloseRequestedAtUtc: string | null; lastManagedAtUtc: string | null; lastReason: string | null; createdAtUtc: string; updatedAtUtc: string }
export type DemoStrategySymbol = { symbol: string; brokerSymbol: string; lastProcessedClosedCandleUtc: string | null; lastMarketEventUtc: string | null; trendRegimeDirection: string | null; trendRegimeCrossoverTimeUtc: string | null; reentryEligible: boolean; reentryConsumed: boolean; reentrySourceDemoExecutionId: number | null; reentryEligibleAtUtc: string | null; reentryReason: string | null; recentIntents: DemoStrategyIntent[]; management: DemoStrategyManagement[] }
export type DemoStrategyRuntime = { sessionId: number; connectionState: string; lastUpdateUtc: string | null; lastClosedCandles: Record<string, string | null> }
export type DemoStrategySession = { id: number; interval: string; status: string; createdAtUtc: string; startedAtUtc: string | null; stoppedAtUtc: string | null; interruptedAtUtc: string | null; failureMessage: string | null; automationEnabled: boolean; managementEnabled: boolean; automationEnabledAtCreation: boolean; fixedLots: number; riskReward: number; minEmaGapPercent: number; maxStopDistancePercent: number; waitForConfirmationCandle: boolean; useEma100Filter: boolean; useAdaptiveInitialStop: boolean; trailingStopEnabled: boolean; exitOnOppositeCrossover: boolean; sameTrendReentryEnabled: boolean; maxReentryAgeBars: number; initialAllocation: number; budget: { initialAllocation: number; accountCurrency: string | null; realizedPnl: number | null; unrealizedPnl: number | null; balance: number | null; equity: number | null; evidenceReady: boolean; reason: string | null }; symbols: DemoStrategySymbol[]; runtime: DemoStrategyRuntime | null }
export type DemoStrategySessionSummary = { id: number; interval: string; status: string; createdAtUtc: string; startedAtUtc: string | null; stoppedAtUtc: string | null; interruptedAtUtc: string | null; failureMessage: string | null; symbolCount: number; symbols: string[]; automationEnabledAtCreation: boolean; trailingStopEnabled: boolean; exitOnOppositeCrossover: boolean; sameTrendReentryEnabled: boolean; fixedLots: number; riskReward: number; initialAllocation: number }
export const getDemoAutomationSafety = () => request<DemoAutomationSafety>('/api/demo-strategy-sessions/safety')
export const getCurrentDemoStrategySession = () => request<DemoStrategySession | undefined>('/api/demo-strategy-sessions/current')
export const getDemoStrategySessions = () => request<DemoStrategySessionSummary[]>('/api/demo-strategy-sessions')
export const getDemoStrategySession = (id: number) => request<DemoStrategySession>(`/api/demo-strategy-sessions/${id}`)
export const getDemoStrategyRuntime = (id: number) => request<DemoStrategyRuntime | null>(`/api/demo-strategy-sessions/${id}/runtime`)
export const createDemoStrategySession = (interval: string, symbols: string[], initialAllocation = 100) => protectedRequest<DemoStrategySession>('/api/demo-strategy-sessions', 'POST', { interval, symbols, initialAllocation })
export const startDemoStrategySession = (id: number) => protectedRequest<DemoStrategySession>(`/api/demo-strategy-sessions/${id}/start`, 'POST')
export const resumeDemoStrategySession = (id: number) => protectedRequest<DemoStrategySession>(`/api/demo-strategy-sessions/${id}/resume`, 'POST')
export const stopDemoStrategySession = (id: number) => protectedRequest<void>(`/api/demo-strategy-sessions/${id}/stop`, 'POST')

async function protectedRequest<T>(path: string, method: string, body?: unknown, signal?: AbortSignal): Promise<T> {
  const token = await antiforgeryToken(signal)
  return request<T>(path, { method, headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': token }, body: body === undefined ? undefined : JSON.stringify(body), signal })
}

export const getMonitoredSymbols = () => request<MonitoredSymbol[]>('/api/symbols')
export const getInstruments = () => request<InstrumentCatalogItem[]>('/api/instruments')
export const addMonitoredSymbol = (brokerSymbol: string) => protectedRequest<MonitoredSymbol>('/api/symbols', 'POST', { brokerSymbol })
export const setSymbolEnabled = (id: number, isEnabled: boolean) => protectedRequest<MonitoredSymbol>(`/api/symbols/${id}/enabled`, 'PATCH', { isEnabled })
export const setPaperCommission = (id: number, commissionPerLotPerSide: number) => protectedRequest<MonitoredSymbol>(`/api/symbols/${id}/paper-costs`, 'PATCH', { commissionPerLotPerSide })
export const removeMonitoredSymbol = (id: number) => protectedRequest<void>(`/api/symbols/${id}`, 'DELETE')
export const getTradingSettings = () => request<TradingSettings>('/api/settings/trading')
export const updateTradingSettings = (settings: Omit<TradingSettings, 'updatedAtUtc'>) => protectedRequest<TradingSettings>('/api/settings/trading', 'PUT', settings)
export const getBacktests = () => request<BacktestRunSummary[]>('/api/backtests')
export const getMt5HistoricalBacktestEconomicsPreview = (symbol: string) => request<Mt5HistoricalBacktestEconomicsPreview>(`/api/backtests/economics-preview?symbol=${encodeURIComponent(symbol)}`)
export const getBacktest = (id: number) => request<BacktestRun>(`/api/backtests/${id}`)
export const runBacktest = (requestBody: { symbol: string; interval: string; startUtc: string; endUtc: string }, signal?: AbortSignal) => protectedRequest<BacktestRun>('/api/backtests', 'POST', requestBody, signal)
export const deleteBacktest = (id: number) => protectedRequest<void>(`/api/backtests/${id}`, 'DELETE')
export async function downloadBacktestExcel(id: number) { await download(`/api/backtests/${id}/export/excel`, `ema-bot-backtest-${id}.xlsx`) }
export const getOptimizerOptions = () => request<OptimizerOptions>('/api/strategy-optimizer/options')
export const getOptimizerRuns = () => request<OptimizerRun[]>('/api/strategy-optimizer/runs')
export const getOptimizerRun = (id: number) => request<OptimizerRun>(`/api/strategy-optimizer/runs/${id}`)
export const getOptimizerCandidates = (id: number, page = 1, pageSize = 50) => request<{ total: number; items: OptimizerCandidate[] }>(`/api/strategy-optimizer/runs/${id}/candidates?page=${page}&pageSize=${pageSize}`)
export const getOptimizerCandidate = (runId: number, candidateId: number) => request<{ candidate: OptimizerCandidate; markets: Array<{ symbol: string; timeframe: string; validation: OptimizerCandidate['validation'] }> }>(`/api/strategy-optimizer/runs/${runId}/candidates/${candidateId}`)
export const startOptimizer = (body: { symbols: string[]; timeframes: string[]; startUtc: string; endUtc: string; grid: OptimizerGrid }) => protectedRequest<OptimizerRun>('/api/strategy-optimizer/runs', 'POST', body)
export const cancelOptimizer = (id: number) => protectedRequest<void>(`/api/strategy-optimizer/runs/${id}/cancel`, 'POST')
export async function downloadOptimizerExcel(id: number) { await download(`/api/strategy-optimizer/runs/${id}/excel`, `ema-bot-optimizer-${id}.xlsx`) }
export async function downloadOptimizerRegimeExcel(runId: number, candidateId: number) { await download(`/api/strategy-optimizer/runs/${runId}/candidates/${candidateId}/regime-excel`, `ema-bot-regime-${runId}-${candidateId}.xlsx`) }
export const getPaperSessions = () => request<PaperSessionSummary[]>('/api/paper-sessions')
export const getActivePaperSession = () => request<PaperSession>('/api/paper-sessions/active')
export const getPaperSession = (id: number) => request<PaperSession>(`/api/paper-sessions/${id}`)
export const getPaperSessionTrades = (id: number, page = 1, pageSize = 50) => request<{ total: number; items: PaperTrade[] }>(`/api/paper-sessions/${id}/trades?page=${page}&pageSize=${pageSize}`)
export const getPaperSessionDecisions = (id: number, page = 1, pageSize = 50, symbol?: string) => request<{ total: number; items: PaperDecision[] }>(`/api/paper-sessions/${id}/decisions?${new URLSearchParams({ page: String(page), pageSize: String(pageSize), ...(symbol ? { symbol } : {}) })}`)
export async function downloadPaperSessionExcel(id: number) { await download(`/api/paper-sessions/${id}/export/excel`, `ema-bot-paper-session-${id}.xlsx`) }
export const startPaperSession = (interval: string, symbols: string[]) => protectedRequest<PaperSession>('/api/paper-sessions', 'POST', { interval, symbols })
export const resumePaperSession = (id: number) => protectedRequest<PaperSession>(`/api/paper-sessions/${id}/resume`, 'POST')
export const stopPaperSession = (id: number) => protectedRequest<void>(`/api/paper-sessions/${id}/stop`, 'POST')
export const getTrades = (filters: Record<string, string>) => request<TradeSummary[]>(`/api/trades?${new URLSearchParams(Object.entries(filters).filter(([, value]) => value)).toString()}`)
export const getTrade = (source: string, id: number, signal?: AbortSignal) => request<TradeDetail | ExnessDemoTradeDetail>(`/api/trades/${source.toLowerCase()}/${id}`, { signal })
export const getTradeChart = (source: string, id: number, signal?: AbortSignal) => request<TradeChartData>(`/api/trades/${source.toLowerCase()}/${id}/chart`, { signal })
export async function downloadTradeExcel(filters: Record<string, string>) { await download(`/api/trade-exports/excel?${new URLSearchParams(Object.entries(filters).filter(([, value]) => value)).toString()}`, 'ema-bot-trades.xlsx') }
export async function downloadDemoStrategySessionExcel(id: number) { await download(`/api/demo-strategy-sessions/${id}/export/excel`, `ema-bot-exness-demo-session-${id}.xlsx`) }
export async function downloadTradePdf(source: string, id: number) { await download(`/api/trade-exports/${source.toLowerCase()}/${id}/pdf`, `ema-bot-trade-${source.toLowerCase()}-${id}.pdf`) }
async function download(path: string, fileName: string) { const response = await fetch(path, { credentials: 'include' }); if (!response.ok) { const body = await response.json().catch(() => ({})) as ApiMessage; throw new ApiError(response.status, body.message ?? 'The export could not be created.') }; const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url) }
