// <auto-generated />
using EmaBot.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EmaBot.Api.Migrations;

[DbContext(typeof(EmaBotDbContext))]
[Migration("20260813173000_PersistPaperDecisionLedger")]
partial class PersistPaperDecisionLedger
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
}
