// <auto-generated />
using System;
using EmaBot.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmaBot.Api.Migrations
{
    [DbContext(typeof(EmaBotDbContext))]
    [Migration("20260812202117_AddOptionalHtfRegimeFilter")]
    partial class AddOptionalHtfRegimeFilter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EmaBot.Api.Auth.EmaUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActualEndUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("ActualStartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("AverageNetPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AverageRMultiple")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("BreakEvenTrades")
                        .HasColumnType("int");

                    b.Property<int>("CandleCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ConfirmationFailed")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("EndingBalanceUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("longtext");

                    b.Property<decimal>("FeePercentPerSide")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FixedOrderSizeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GrossPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("InvalidStopLoss")
                        .HasColumnType("int");

                    b.Property<decimal>("Leverage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("LongSignals")
                        .HasColumnType("int");

                    b.Property<int>("LongTrades")
                        .HasColumnType("int");

                    b.Property<int>("LosingTrades")
                        .HasColumnType("int");

                    b.Property<decimal>("MarginPerTradePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MaxDrawdownUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MaxStopDistancePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MinEmaGapPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("NetPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("NoEntryCandle")
                        .HasColumnType("int");

                    b.Property<int>("PositionSizingMode")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProfitFactor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RejectedByEma100")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByEmaGap")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByFees")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByHtfRegime")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByStopDistance")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RequestedEndUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("RequestedStartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("RiskReward")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ShortSignals")
                        .HasColumnType("int");

                    b.Property<int>("ShortTrades")
                        .HasColumnType("int");

                    b.Property<int>("SkippedWhilePositionOpen")
                        .HasColumnType("int");

                    b.Property<decimal>("StartingBalanceUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("TotalCrossovers")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFeesUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("int");

                    b.Property<bool>("TrailingStopEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseEma100Filter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseHtfRegimeFilter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("WaitForConfirmationCandle")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("WinRatePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AccountEquityAtEntryUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("BacktestRunId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<decimal>("EntryFeeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("EntryNotionalUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("EntryTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ExitFeeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ExitReason")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExitTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("FinalStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FinalTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GrossPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GrossRMultiple")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("HtfTimeframe")
                        .HasColumnType("longtext");

                    b.Property<decimal>("InitialStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsReentry")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Leverage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MaePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MaePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MarginUsedUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("MfePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MfePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetPnlPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetRMultiple")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OriginalTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PositionSizingMode")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("SameCandleExitConflict")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("SignalClose")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma100")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma15")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma9")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalGapPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SignalGapState")
                        .HasColumnType("int");

                    b.Property<decimal?>("SignalHtfAtr14Percent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("SignalHtfCandleCloseTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("SignalHtfEma100Slope20Percent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalOpen")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("SignalTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("StopSourceTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StopSourceType")
                        .HasColumnType("int");

                    b.Property<bool>("TakeProfitExtended")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TotalFeesUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("TrendRegimeCrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId");

                    b.ToTable("BacktestTrades");
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestTradeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacktestTradeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EffectiveTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MarketPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NewStop")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NewTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OldStop")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OldTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ProgressPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("TimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacktestTradeId");

                    b.ToTable("BacktestTradeEvents");
                });

            modelBuilder.Entity("EmaBot.Api.Models.MonitoredSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("MonitoredSymbols");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletedTrades")
                        .HasColumnType("int");

                    b.Property<int>("ConfirmationFailed")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentBalanceUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("longtext");

                    b.Property<decimal>("FeePercentPerSide")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("FixedOrderSizeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("InterruptedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("InvalidStopLoss")
                        .HasColumnType("int");

                    b.Property<decimal>("Leverage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("LongSignals")
                        .HasColumnType("int");

                    b.Property<decimal>("MarginPerTradePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MaxStopDistancePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MinEmaGapPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("NetPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PositionSizingMode")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByEma100")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByEmaGap")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByFees")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByInsufficientMargin")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByStopDistance")
                        .HasColumnType("int");

                    b.Property<decimal>("RiskReward")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ShortSignals")
                        .HasColumnType("int");

                    b.Property<int>("SkippedWhilePositionOpen")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("StartingBalanceUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StoppedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalCrossovers")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFeesUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("TrailingStopEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseEma100Filter")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("UsedMarginUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("WaitForConfirmationCandle")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("PaperSessions");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperSessionSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("LastKnownPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("LastMarketEventUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("LastProcessedClosedCandleUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaperSessionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PendingCrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PendingDirection")
                        .HasColumnType("int");

                    b.Property<bool>("PendingIsReentry")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("PendingSignalClose")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PendingSignalEma100")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PendingSignalEma15")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PendingSignalEma9")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PendingSignalGapPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("PendingSignalGapState")
                        .HasColumnType("int");

                    b.Property<decimal?>("PendingSignalOpen")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("PendingSignalTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("PendingStopPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("PendingStopSourceTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PendingStopSourceType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PendingTrendRegimeCrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ReentryConsumed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReentryEligible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset?>("TrendRegimeCrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TrendRegimeDirection")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaperSessionId", "Symbol")
                        .IsUnique();

                    b.ToTable("PaperSessionSymbols");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AccountEquityAtEntryUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("BestFavorableProgressPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("CrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CurrentTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<decimal>("EntryFeeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("EntryNotionalUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("EntryTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("ExitFeeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ExitReason")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ExitTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("FinalStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("FinalTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GrossPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("InitialStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<bool>("IsReentry")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Leverage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MaePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MaePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MarginUsedUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("MfePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MfePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetPnlPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OriginalTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PaperSessionId")
                        .HasColumnType("int");

                    b.Property<int>("PaperSessionSymbolId")
                        .HasColumnType("int");

                    b.Property<int>("PositionSizingMode")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SignalClose")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma100")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma15")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma9")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalGapPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SignalGapState")
                        .HasColumnType("int");

                    b.Property<decimal?>("SignalOpen")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("SignalTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StopSourceTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StopSourceType")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("TakeProfitExtended")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TotalFeesUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("TrendRegimeCrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PaperSessionId");

                    b.HasIndex("PaperSessionSymbolId", "Status");

                    b.ToTable("PaperTrades");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperTradeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MarketPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NewStop")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NewTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OldStop")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OldTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PaperTradeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProgressPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("TimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaperTradeId");

                    b.ToTable("PaperTradeEvents");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Development")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Full")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MaxStopDistancePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MinEmaGapPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ProfitableMarketRatio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RiskReward")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("RobustCandidate")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("RobustRank")
                        .HasColumnType("int");

                    b.Property<int>("StrategyOptimizationRunId")
                        .HasColumnType("int");

                    b.Property<bool>("TrailingStopEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseEma100Filter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseHtfRegimeFilter")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Validation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WaitForConfirmationCandle")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyOptimizationRunId", "RobustRank");

                    b.ToTable("StrategyOptimizationCandidates");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationMarketResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Development")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Full")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StrategyOptimizationCandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Validation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("StrategyOptimizationCandidateId", "Symbol", "Timeframe")
                        .IsUnique();

                    b.ToTable("StrategyOptimizationMarketResults");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaselineSettingsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CompletedWork")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("longtext");

                    b.Property<decimal>("FeePercentPerSide")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FixedOrderSizeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("GridJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Leverage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MarginPerTradePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MarketCount")
                        .HasColumnType("int");

                    b.Property<int>("PositionSizingMode")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendedCandidateId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RequestedEndUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("RequestedStartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("SimulatedAccountBalanceUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SymbolsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TimeframesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalWork")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("StrategyOptimizationRuns");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("EntryTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ExitReason")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExitTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ExpectedNetTargetR")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FinalStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FinalTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GrossPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("InitialStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsReentry")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("NetPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetRMultiple")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OriginalTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma100")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma15")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma9")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalGapPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("StrategyOptimizationCandidateId")
                        .HasColumnType("int");

                    b.Property<int>("StrategyOptimizationRunId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("TotalFeesUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyOptimizationRunId", "StrategyOptimizationCandidateId");

                    b.ToTable("StrategyOptimizationTrades");
                });

            modelBuilder.Entity("EmaBot.Api.Models.TradingSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("FeePercentPerSide")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("FixedOrderSizeUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Leverage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MarginPerTradePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MaxStopDistancePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MinEmaGapPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("PositionSizingMode")
                        .HasColumnType("int");

                    b.Property<decimal>("RiskReward")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("SimulatedAccountBalanceUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("TrailingStopEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("UseEma100Filter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseHtfRegimeFilter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("WaitForConfirmationCandle")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("TradingSettings", t =>
                        {
                            t.HasCheckConstraint("CK_TradingSettings_Singleton", "`Id` = 1");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestTrade", b =>
                {
                    b.HasOne("EmaBot.Api.Models.BacktestRun", "BacktestRun")
                        .WithMany("Trades")
                        .HasForeignKey("BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestTradeEvent", b =>
                {
                    b.HasOne("EmaBot.Api.Models.BacktestTrade", "BacktestTrade")
                        .WithMany("Events")
                        .HasForeignKey("BacktestTradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestTrade");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperSessionSymbol", b =>
                {
                    b.HasOne("EmaBot.Api.Models.PaperSession", "PaperSession")
                        .WithMany("Symbols")
                        .HasForeignKey("PaperSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaperSession");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperTrade", b =>
                {
                    b.HasOne("EmaBot.Api.Models.PaperSession", "PaperSession")
                        .WithMany("Trades")
                        .HasForeignKey("PaperSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmaBot.Api.Models.PaperSessionSymbol", "PaperSessionSymbol")
                        .WithMany("Trades")
                        .HasForeignKey("PaperSessionSymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaperSession");

                    b.Navigation("PaperSessionSymbol");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperTradeEvent", b =>
                {
                    b.HasOne("EmaBot.Api.Models.PaperTrade", "PaperTrade")
                        .WithMany("Events")
                        .HasForeignKey("PaperTradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaperTrade");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationCandidate", b =>
                {
                    b.HasOne("EmaBot.Api.Models.StrategyOptimizationRun", "StrategyOptimizationRun")
                        .WithMany("Candidates")
                        .HasForeignKey("StrategyOptimizationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategyOptimizationRun");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationMarketResult", b =>
                {
                    b.HasOne("EmaBot.Api.Models.StrategyOptimizationCandidate", "StrategyOptimizationCandidate")
                        .WithMany("MarketResults")
                        .HasForeignKey("StrategyOptimizationCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategyOptimizationCandidate");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationTrade", b =>
                {
                    b.HasOne("EmaBot.Api.Models.StrategyOptimizationRun", null)
                        .WithMany("Trades")
                        .HasForeignKey("StrategyOptimizationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EmaBot.Api.Auth.EmaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EmaBot.Api.Auth.EmaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmaBot.Api.Auth.EmaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EmaBot.Api.Auth.EmaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestRun", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestTrade", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperSession", b =>
                {
                    b.Navigation("Symbols");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperSessionSymbol", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperTrade", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationCandidate", b =>
                {
                    b.Navigation("MarketResults");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationRun", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
