// <auto-generated />
using System;
using EmaBot.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmaBot.Api.Migrations
{
    [DbContext(typeof(EmaBotDbContext))]
    partial class EmaBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EmaBot.Api.Auth.EmaUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActualEndUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("ActualStartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("AverageNetPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AverageRMultiple")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("BreakEvenTrades")
                        .HasColumnType("int");

                    b.Property<int>("CandleCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ConfirmationFailed")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("EndingBalanceUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("longtext");

                    b.Property<decimal>("FeePercentPerSide")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FixedOrderSizeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GrossPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("InvalidStopLoss")
                        .HasColumnType("int");

                    b.Property<decimal>("Leverage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("LongSignals")
                        .HasColumnType("int");

                    b.Property<int>("LongTrades")
                        .HasColumnType("int");

                    b.Property<int>("LosingTrades")
                        .HasColumnType("int");

                    b.Property<decimal>("MarginPerTradePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("MarketDataSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("LegacyBinance");

                    b.Property<decimal>("MaxDrawdownUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("ExitOnOppositeCrossover")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxReentryAgeBars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(6);

                    b.Property<decimal>("MaxStopDistancePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MinEmaGapPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("NetPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("NoEntryCandle")
                        .HasColumnType("int");

                    b.Property<int>("PositionSizingMode")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProfitFactor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RejectedByEma100")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByEmaGap")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByFees")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByHtfRegime")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByStopDistance")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RequestedEndUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("RequestedStartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("RiskReward")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("SameTrendReentryEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ShortSignals")
                        .HasColumnType("int");

                    b.Property<int>("ShortTrades")
                        .HasColumnType("int");

                    b.Property<int>("SkippedWhilePositionOpen")
                        .HasColumnType("int");

                    b.Property<decimal>("StartingBalanceUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("TotalCrossovers")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFeesUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("int");

                    b.Property<bool>("TrailingStopEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseAdaptiveInitialStop")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseEma100Filter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseHtfRegimeFilter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("WaitForConfirmationCandle")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("WinRatePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("WinningTrades")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BacktestRuns");
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AccountEquityAtEntryUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("BacktestRunId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<decimal>("EntryFeeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("EntryNotionalUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("EntryTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ExitFeeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ExitReason")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExitTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("FinalStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FinalTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GrossPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GrossRMultiple")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("HtfTimeframe")
                        .HasColumnType("longtext");

                    b.Property<decimal>("InitialStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsReentry")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Leverage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MaePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MaePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MarginUsedUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("MfePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MfePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetPnlPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetRMultiple")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OriginalTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PositionSizingMode")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ReversalPowerBand")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReversalPowerScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<bool>("SameCandleExitConflict")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("SignalAtr14")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("SignalClose")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma100")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma15")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma9")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalGapPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SignalGapState")
                        .HasColumnType("int");

                    b.Property<decimal?>("SignalHtfAtr14Percent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("SignalHtfCandleCloseTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("SignalHtfEma100Slope20Percent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalOpen")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("SignalTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("StopAnchorPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("StopBuffer")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("StopSourceTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StopSourceType")
                        .HasColumnType("int");

                    b.Property<bool>("TakeProfitExtended")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TotalFeesUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("TrendRegimeCrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("UseAdaptiveInitialStop")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("BacktestRunId");

                    b.ToTable("BacktestTrades");
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestTradeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacktestTradeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EffectiveTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MarketPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NewStop")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NewTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OldStop")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OldTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ProgressPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("TimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacktestTradeId");

                    b.ToTable("BacktestTradeEvents");
                });

            modelBuilder.Entity("EmaBot.Api.Models.MonitoredSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("PaperCommissionPerLotPerSide")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("QuoteAsset")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("LegacyBinance");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_bin");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Symbol")
                        .IsUnique();

                    b.ToTable("MonitoredSymbols");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoExecution", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                    b.Property<decimal?>("AverageFillPrice").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal?>("AverageClosePrice").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<string>("BrokerMessage").HasMaxLength(1024).HasColumnType("varchar(1024)");
                    b.Property<string>("BrokerRetcode").HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<string>("BrokerSymbol").IsRequired().HasMaxLength(64).HasColumnType("varchar(64)").UseCollation("utf8mb4_bin");
                    b.Property<DateTimeOffset?>("BrokerAcceptedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("BrokerClosedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("BrokerExecutedAtUtc").HasColumnType("datetime(6)");
                    b.Property<decimal?>("ClosedVolumeLots").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<DateTimeOffset?>("ClosedAtUtc").HasColumnType("datetime(6)");
                    b.Property<Guid>("ClientExecutionId").HasColumnType("char(36)");
                    b.Property<string>("CorrelationMarker").IsRequired().HasMaxLength(96).HasColumnType("varchar(96)");
                    b.Property<decimal?>("CurrentStopLoss").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal?>("CurrentTakeProfit").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<long?>("DealTicket").HasColumnType("bigint");
                    b.Property<long?>("EntryDealTicket").HasColumnType("bigint");
                    b.Property<long?>("ExitDealTicket").HasColumnType("bigint");
                    b.Property<string>("ExpectedAccountFingerprint").IsRequired().HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<string>("ExpectedServer").IsRequired().HasMaxLength(256).HasColumnType("varchar(256)");
                    b.Property<decimal?>("FilledVolumeLots").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<long>("MagicNumber").HasColumnType("bigint");
                    b.Property<string>("NativeExitReason").HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<bool>("NativeExitReasonConflicted").HasDefaultValue(false).HasColumnType("tinyint(1)");
                    b.Property<long?>("OrderTicket").HasColumnType("bigint");
                    b.Property<long?>("PositionIdentifier").HasColumnType("bigint");
                    b.Property<long?>("PositionTicket").HasColumnType("bigint");
                    b.Property<DateTimeOffset?>("ProtectionObservedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("PreflightAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("Provider").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.Property<DateTimeOffset?>("ReconciledAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("ReconciliationNote").HasMaxLength(1024).HasColumnType("varchar(1024)");
                    b.Property<string>("ReconciliationSource").HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<decimal?>("RequestedStopLoss").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal?>("RequestedTakeProfit").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<string>("Side").IsRequired().HasMaxLength(8).HasColumnType("varchar(8)");
                    b.Property<string>("State").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.Property<DateTimeOffset?>("SubmittedAtUtc").HasColumnType("datetime(6)");
                    b.Property<decimal>("VolumeLots").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.HasKey("Id"); b.HasIndex("ClientExecutionId").IsUnique(); b.HasIndex("PositionIdentifier"); b.HasIndex("PositionTicket"); b.HasIndex("State"); b.ToTable("DemoExecutions");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoExecutionManagementAction", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                    b.Property<decimal?>("AppliedStopLoss").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal?>("AppliedTakeProfit").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<string>("BrokerMessage").HasMaxLength(1024).HasColumnType("varchar(1024)");
                    b.Property<string>("BrokerRetcode").HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<Guid>("ClientManagementActionId").HasColumnType("char(36)");
                    b.Property<DateTimeOffset?>("CompletedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<int>("DemoExecutionId").HasColumnType("int");
                    b.Property<string>("Kind").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.Property<decimal?>("ObservedBeforeStopLoss").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal?>("ObservedBeforeTakeProfit").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<DateTimeOffset?>("ReconciledAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("ReconciliationNote").HasMaxLength(1024).HasColumnType("varchar(1024)");
                    b.Property<string>("ReconciliationSource").HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<decimal?>("RequestedStopLoss").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal?>("RequestedTakeProfit").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<string>("State").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.Property<DateTimeOffset?>("SubmittedAtUtc").HasColumnType("datetime(6)");
                    b.HasKey("Id"); b.HasIndex("ClientManagementActionId").IsUnique(); b.HasIndex("DemoExecutionId", "State"); b.ToTable("DemoExecutionManagementActions");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoExecutionManagementAction", b =>
                {
                    b.HasOne("EmaBot.Api.Models.DemoExecution", "DemoExecution").WithMany("ManagementActions").HasForeignKey("DemoExecutionId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("DemoExecution");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoStrategyIntent", b =>
                {
                    b.HasOne("EmaBot.Api.Models.DemoExecution", "DemoExecution").WithMany().HasForeignKey("DemoExecutionId").OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("EmaBot.Api.Models.DemoStrategySession", "DemoStrategySession").WithMany("Intents").HasForeignKey("DemoStrategySessionId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("EmaBot.Api.Models.DemoStrategySessionSymbol", "DemoStrategySessionSymbol").WithMany("Intents").HasForeignKey("DemoStrategySessionSymbolId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("DemoExecution"); b.Navigation("DemoStrategySession"); b.Navigation("DemoStrategySessionSymbol");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoStrategySessionSymbol", b =>
                {
                    b.HasOne("EmaBot.Api.Models.DemoStrategySession", "DemoStrategySession").WithMany("Symbols").HasForeignKey("DemoStrategySessionId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("DemoStrategySession");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoStrategyPositionManagement", b =>
                {
                    b.HasOne("EmaBot.Api.Models.DemoExecution", "DemoExecution").WithMany().HasForeignKey("DemoExecutionId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("EmaBot.Api.Models.DemoStrategyIntent", "DemoStrategyIntent").WithMany().HasForeignKey("DemoStrategyIntentId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("EmaBot.Api.Models.DemoStrategySession", "DemoStrategySession").WithMany("PositionManagement").HasForeignKey("DemoStrategySessionId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("EmaBot.Api.Models.DemoStrategySessionSymbol", "DemoStrategySessionSymbol").WithMany().HasForeignKey("DemoStrategySessionSymbolId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("DemoExecution"); b.Navigation("DemoStrategyIntent"); b.Navigation("DemoStrategySession"); b.Navigation("DemoStrategySessionSymbol");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoStrategyIntent", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                    b.Property<Guid>("ClientExecutionId").HasColumnType("char(36)");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset>("CrossoverTimeUtc").HasColumnType("datetime(6)");
                    b.Property<int?>("DemoExecutionId").HasColumnType("int");
                    b.Property<int>("DemoStrategySessionId").HasColumnType("int");
                    b.Property<int>("DemoStrategySessionSymbolId").HasColumnType("int");
                    b.Property<string>("Direction").IsRequired().HasMaxLength(8).HasColumnType("varchar(8)");
                    b.Property<DateTimeOffset>("ExpectedEntryOpenUtc").HasColumnType("datetime(6)");
                    b.Property<decimal>("IntendedVolumeLots").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal?>("IntendedTakeProfit").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<string>("Reason").HasMaxLength(1024).HasColumnType("varchar(1024)");
                    b.Property<decimal?>("SignalEma100").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal?>("SignalEma15").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal?>("SignalEma9").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal?>("SignalGapPercent").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<string>("SignalGapState").IsRequired().HasMaxLength(16).HasColumnType("varchar(16)");
                    b.Property<decimal>("SignalClose").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal>("SignalOpen").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<DateTimeOffset>("SignalTimeUtc").HasColumnType("datetime(6)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.Property<decimal>("StructuralStopLoss").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<string>("StopSourceType").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.Property<DateTimeOffset>("StopSourceTimeUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("SubmittedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("UpdatedAtUtc").HasColumnType("datetime(6)");
                    b.HasKey("Id"); b.HasIndex("ClientExecutionId").IsUnique(); b.HasIndex("DemoExecutionId"); b.HasIndex("DemoStrategySessionSymbolId", "Status"); b.HasIndex("DemoStrategySessionId", "DemoStrategySessionSymbolId", "SignalTimeUtc", "Direction").IsUnique(); b.ToTable("DemoStrategyIntents");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoExecution", b =>
                {
                    b.Navigation("ManagementActions");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoStrategySession", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("AutomationEnabledAtCreation").HasColumnType("tinyint(1)");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<bool>("ExitOnOppositeCrossover").HasColumnType("tinyint(1)");
                    b.Property<string>("FailureMessage").HasMaxLength(1024).HasColumnType("varchar(1024)");
                    b.Property<decimal>("FixedLots").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<DateTimeOffset?>("InterruptedAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("Interval").IsRequired().HasMaxLength(8).HasColumnType("varchar(8)");
                    b.Property<decimal>("MaxStopDistancePercent").HasPrecision(8, 4).HasColumnType("decimal(8,4)");
                    b.Property<int>("MaxReentryAgeBars").HasDefaultValue(6).HasColumnType("int");
                    b.Property<decimal>("MinEmaGapPercent").HasPrecision(8, 4).HasColumnType("decimal(8,4)");
                    b.Property<decimal>("RiskReward").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<bool>("SameTrendReentryEnabled").HasColumnType("tinyint(1)");
                    b.Property<DateTimeOffset?>("StartedAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.Property<DateTimeOffset?>("StoppedAtUtc").HasColumnType("datetime(6)");
                    b.Property<bool>("TrailingStopEnabled").HasColumnType("tinyint(1)");
                    b.Property<bool>("UseAdaptiveInitialStop").HasColumnType("tinyint(1)");
                    b.Property<bool>("UseEma100Filter").HasColumnType("tinyint(1)");
                    b.Property<bool>("WaitForConfirmationCandle").HasColumnType("tinyint(1)");
                    b.HasKey("Id"); b.HasIndex("Status"); b.ToTable("DemoStrategySessions");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoStrategyPositionManagement", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                    b.Property<decimal>("BestFavorableProgressPercent").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal?>("BestFavorablePrice").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("datetime(6)");
                    b.Property<int>("DemoExecutionId").HasColumnType("int");
                    b.Property<int>("DemoStrategyIntentId").HasColumnType("int");
                    b.Property<int>("DemoStrategySessionId").HasColumnType("int");
                    b.Property<int>("DemoStrategySessionSymbolId").HasColumnType("int");
                    b.Property<decimal>("HighestAppliedLockPercent").HasPrecision(8, 4).HasColumnType("decimal(8,4)");
                    b.Property<decimal>("HighestAttemptedLockPercent").HasPrecision(8, 4).HasColumnType("decimal(8,4)");
                    b.Property<string>("LastReason").HasMaxLength(1024).HasColumnType("varchar(1024)");
                    b.Property<DateTimeOffset?>("LastManagedAtUtc").HasColumnType("datetime(6)");
                    b.Property<decimal>("OriginalEntryPrice").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal>("OriginalStopLoss").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal>("OriginalTakeProfit").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<string>("OppositeCloseState").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.Property<DateTimeOffset?>("OppositeCloseRequestedAtUtc").HasColumnType("datetime(6)");
                    b.Property<string>("OppositeSignalDirection").HasMaxLength(8).HasColumnType("varchar(8)");
                    b.Property<DateTimeOffset?>("OppositeSignalTimeUtc").HasColumnType("datetime(6)");
                    b.Property<Guid?>("PendingProtectionActionId").HasColumnType("char(36)");
                    b.Property<bool>("PendingProtectionExtendsTarget").HasColumnType("tinyint(1)");
                    b.Property<decimal?>("PendingProtectionLockPercent").HasPrecision(8, 4).HasColumnType("decimal(8,4)");
                    b.Property<decimal?>("PendingDesiredStopLoss").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<decimal?>("PendingDesiredTakeProfit").HasPrecision(18, 8).HasColumnType("decimal(18,8)");
                    b.Property<string>("State").IsRequired().HasMaxLength(48).HasColumnType("varchar(48)");
                    b.Property<string>("TakeProfitExtensionState").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.Property<DateTimeOffset?>("TargetExtensionAppliedAtUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("datetime(6)");
                    b.HasKey("Id"); b.HasIndex("DemoExecutionId").IsUnique(); b.HasIndex("DemoStrategyIntentId"); b.HasIndex("DemoStrategySessionId", "State"); b.HasIndex("DemoStrategySessionSymbolId"); b.ToTable("DemoStrategyPositionManagement");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoStrategySessionSymbol", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("BrokerSymbol").IsRequired().HasMaxLength(64).HasColumnType("varchar(64)").UseCollation("utf8mb4_bin");
                    b.Property<int>("DemoStrategySessionId").HasColumnType("int");
                    b.Property<DateTimeOffset?>("LastMarketEventUtc").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("LastProcessedClosedCandleUtc").HasColumnType("datetime(6)");
                    b.Property<string>("Symbol").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.HasKey("Id"); b.HasIndex("DemoStrategySessionId", "Symbol").IsUnique(); b.ToTable("DemoStrategySessionSymbols");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperDecisionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Ask")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("Bid")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset?>("CandleCloseTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Direction")
                        .HasColumnType("int");

                    b.Property<decimal?>("Ema100")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("Ema15")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("Ema9")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("EntryPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset?>("ExpectedEntryOpenUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("GapPercent")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int?>("GapState")
                        .HasColumnType("int");

                    b.Property<decimal?>("Lots")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("PaperSessionId")
                        .HasColumnType("int");

                    b.Property<int>("PaperSessionSymbolId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RequiredMargin")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal?>("StopPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int?>("StopSource")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PaperSessionId", "TimeUtc");

                    b.HasIndex("PaperSessionSymbolId", "TimeUtc");

                    b.ToTable("PaperDecisionEvents");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("USDT");

                    b.Property<int>("CompletedTrades")
                        .HasColumnType("int");

                    b.Property<int>("ConfirmationFailed")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("CurrentBalanceUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("longtext");

                    b.Property<decimal>("FeePercentPerSide")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<bool>("ExitOnOppositeCrossover")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<decimal>("FixedOrderSizeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("InterruptedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("InvalidStopLoss")
                        .HasColumnType("int");

                    b.Property<decimal>("Leverage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("LongSignals")
                        .HasColumnType("int");

                    b.Property<decimal>("MarginPerTradePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("MarketDataSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("LegacyBinance");

                    b.Property<int>("MaxReentryAgeBars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(6);

                    b.Property<decimal>("MaxStopDistancePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MinEmaGapPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("NetPnl")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("NetPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PaperFixedLots")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("PaperMarginPerTradePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("PaperPositionSizingMode")
                        .HasColumnType("int");

                    b.Property<int>("PositionSizingMode")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByEma100")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByEmaGap")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByFees")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByInsufficientMargin")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByInvalidVolume")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByExecutableStop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RejectedByStopDistance")
                        .HasColumnType("int");

                    b.Property<int>("RejectedByTradingCosts")
                        .HasColumnType("int");

                    b.Property<decimal>("RiskReward")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("SameTrendReentryEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ShortSignals")
                        .HasColumnType("int");

                    b.Property<int>("SkippedWhilePositionOpen")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("StartingBalance")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("StartingBalanceUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StoppedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalCrossovers")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFeesUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalTradingCosts")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("TrailingStopEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseAdaptiveInitialStop")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseEma100Filter")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("UsedMargin")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("UsedMarginUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("WaitForConfirmationCandle")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("PaperSessions");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperSessionSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrokerSymbol")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .UseCollation("utf8mb4_bin");

                    b.Property<decimal?>("CommissionPerLotPerSide")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("ContractSize")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("LastKnownPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("LastMarketEventUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("LastProcessedClosedCandleUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaperSessionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PendingCrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PendingDirection")
                        .HasColumnType("int");

                    b.Property<int?>("PendingOppositeExitDirection")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PendingOppositeExitSignalTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("PendingIsReentry")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PendingReversalPowerBand")
                        .HasColumnType("int");

                    b.Property<decimal?>("PendingReversalPowerScore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PendingSignalAtr14")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PendingSignalClose")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PendingSignalEma100")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PendingSignalEma15")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PendingSignalEma9")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PendingSignalGapPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("PendingSignalGapState")
                        .HasColumnType("int");

                    b.Property<decimal?>("PendingSignalOpen")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("PendingSignalTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("PendingStopAnchorPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PendingStopBuffer")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PendingStopPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("PendingStopSourceTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PendingStopSourceType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PendingTrendRegimeCrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("PointSize")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("ReentryConsumed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReentryEligible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("StopsLevelPoints")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<decimal?>("TickSize")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("TickValueLoss")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("TickValueProfit")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int?>("TradeMode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("TrendRegimeCrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TrendRegimeDirection")
                        .HasColumnType("int");

                    b.Property<decimal?>("VolumeLimit")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("VolumeMax")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("VolumeMin")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("VolumeStep")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("PaperSessionId", "Symbol")
                        .IsUnique();

                    b.ToTable("PaperSessionSymbols");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AccountEquityAtEntry")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("AccountEquityAtEntryUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("BestFavorableProgressPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("CrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CurrentTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<decimal?>("EntryAsk")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("EntryBid")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("EntryFeeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("EntryNotionalUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("EntrySpread")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("EntryTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("ExitAsk")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("ExitBid")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("ExitFeeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ExitReason")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExitSpread")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset?>("ExitTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("FinalStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("FinalTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("GrossPnl")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("GrossPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("InitialStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<bool>("IsReentry")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Leverage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("Lots")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("MaePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MaePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MarginUsed")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("InitialRiskAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("MarginUsedUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("MfePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MfePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NetPnl")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("NetPnlPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OriginalTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PaperSessionId")
                        .HasColumnType("int");

                    b.Property<int>("PaperSessionSymbolId")
                        .HasColumnType("int");

                    b.Property<int>("PositionSizingMode")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ReentryAgeBars")
                        .HasColumnType("int");

                    b.Property<decimal?>("RequiredMargin")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int?>("ReversalPowerBand")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReversalPowerScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("RoundTripCommission")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("SignalAtr14")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("SignalClose")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma100")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma15")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma9")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalGapPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SignalGapState")
                        .HasColumnType("int");

                    b.Property<decimal?>("SignalOpen")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("SignalTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("StopAnchorPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("StopBuffer")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("StopSourceTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StopSourceType")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("TakeProfitExtended")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TotalFeesUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("TrendRegimeCrossoverTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("UseAdaptiveInitialStop")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("PaperSessionId");

                    b.HasIndex("PaperSessionSymbolId", "Status");

                    b.ToTable("PaperTrades");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperTradeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MarketPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NewStop")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NewTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OldStop")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("OldTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PaperTradeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProgressPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("TimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaperTradeId");

                    b.ToTable("PaperTradeEvents");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Development")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Full")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MaxStopDistancePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MinEmaGapPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ProfitableMarketRatio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RiskReward")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("RobustCandidate")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("RobustRank")
                        .HasColumnType("int");

                    b.Property<int>("StrategyOptimizationRunId")
                        .HasColumnType("int");

                    b.Property<bool>("TrailingStopEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseEma100Filter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseHtfRegimeFilter")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Validation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("WaitForConfirmationCandle")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyOptimizationRunId", "RobustRank");

                    b.ToTable("StrategyOptimizationCandidates");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationMarketResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Development")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Full")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StrategyOptimizationCandidateId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Validation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("StrategyOptimizationCandidateId", "Symbol", "Timeframe")
                        .IsUnique();

                    b.ToTable("StrategyOptimizationMarketResults");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaselineSettingsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CompletedWork")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("longtext");

                    b.Property<decimal>("FeePercentPerSide")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FixedOrderSizeUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("GridJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Leverage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("MarginPerTradePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MarketCount")
                        .HasColumnType("int");

                    b.Property<string>("MarketDataSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("LegacyBinance");

                    b.Property<int>("PositionSizingMode")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendedCandidateId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RequestedEndUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("RequestedStartUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("SimulatedAccountBalanceUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SymbolsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TimeframesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalWork")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("StrategyOptimizationRuns");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTimeOffset>("EntryTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ExitReason")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExitTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ExpectedNetTargetR")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FinalStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FinalTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GrossPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("InitialStopLoss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsReentry")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("NetPnlUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetRMultiple")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OriginalTakeProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma100")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma15")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalEma9")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("SignalGapPercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("StrategyOptimizationCandidateId")
                        .HasColumnType("int");

                    b.Property<int>("StrategyOptimizationRunId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("TotalFeesUsdt")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyOptimizationRunId", "StrategyOptimizationCandidateId");

                    b.ToTable("StrategyOptimizationTrades");
                });

            modelBuilder.Entity("EmaBot.Api.Models.TradingSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("FeePercentPerSide")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<bool>("ExitOnOppositeCrossover")
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<decimal>("FixedOrderSizeUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("Leverage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MarginPerTradePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("MaxReentryAgeBars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(6);

                    b.Property<decimal>("MaxStopDistancePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("MinEmaGapPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("PaperFixedLots")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("PaperMarginPerTradePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("PaperPositionSizingMode")
                        .HasColumnType("int");

                    b.Property<decimal>("PaperStartingBalance")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("PositionSizingMode")
                        .HasColumnType("int");

                    b.Property<decimal>("RiskReward")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("SameTrendReentryEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("SimulatedAccountBalanceUsdt")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("TrailingStopEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("UseAdaptiveInitialStop")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseEma100Filter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseHtfRegimeFilter")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("WaitForConfirmationCandle")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("TradingSettings", t =>
                        {
                            t.HasCheckConstraint("CK_TradingSettings_Singleton", "`Id` = 1");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestTrade", b =>
                {
                    b.HasOne("EmaBot.Api.Models.BacktestRun", "BacktestRun")
                        .WithMany("Trades")
                        .HasForeignKey("BacktestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestRun");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoStrategySession", b =>
                {
                    b.Navigation("Intents");
                    b.Navigation("PositionManagement");
                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("EmaBot.Api.Models.DemoStrategySessionSymbol", b =>
                {
                    b.Navigation("Intents");
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestTradeEvent", b =>
                {
                    b.HasOne("EmaBot.Api.Models.BacktestTrade", "BacktestTrade")
                        .WithMany("Events")
                        .HasForeignKey("BacktestTradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestTrade");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperDecisionEvent", b =>
                {
                    b.HasOne("EmaBot.Api.Models.PaperSession", "PaperSession")
                        .WithMany("DecisionEvents")
                        .HasForeignKey("PaperSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmaBot.Api.Models.PaperSessionSymbol", "PaperSessionSymbol")
                        .WithMany("DecisionEvents")
                        .HasForeignKey("PaperSessionSymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaperSession");

                    b.Navigation("PaperSessionSymbol");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperSessionSymbol", b =>
                {
                    b.HasOne("EmaBot.Api.Models.PaperSession", "PaperSession")
                        .WithMany("Symbols")
                        .HasForeignKey("PaperSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaperSession");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperTrade", b =>
                {
                    b.HasOne("EmaBot.Api.Models.PaperSession", "PaperSession")
                        .WithMany("Trades")
                        .HasForeignKey("PaperSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmaBot.Api.Models.PaperSessionSymbol", "PaperSessionSymbol")
                        .WithMany("Trades")
                        .HasForeignKey("PaperSessionSymbolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaperSession");

                    b.Navigation("PaperSessionSymbol");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperTradeEvent", b =>
                {
                    b.HasOne("EmaBot.Api.Models.PaperTrade", "PaperTrade")
                        .WithMany("Events")
                        .HasForeignKey("PaperTradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaperTrade");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationCandidate", b =>
                {
                    b.HasOne("EmaBot.Api.Models.StrategyOptimizationRun", "StrategyOptimizationRun")
                        .WithMany("Candidates")
                        .HasForeignKey("StrategyOptimizationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategyOptimizationRun");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationMarketResult", b =>
                {
                    b.HasOne("EmaBot.Api.Models.StrategyOptimizationCandidate", "StrategyOptimizationCandidate")
                        .WithMany("MarketResults")
                        .HasForeignKey("StrategyOptimizationCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategyOptimizationCandidate");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationTrade", b =>
                {
                    b.HasOne("EmaBot.Api.Models.StrategyOptimizationRun", null)
                        .WithMany("Trades")
                        .HasForeignKey("StrategyOptimizationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EmaBot.Api.Auth.EmaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EmaBot.Api.Auth.EmaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmaBot.Api.Auth.EmaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EmaBot.Api.Auth.EmaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestRun", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("EmaBot.Api.Models.BacktestTrade", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperSession", b =>
                {
                    b.Navigation("DecisionEvents");

                    b.Navigation("Symbols");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperSessionSymbol", b =>
                {
                    b.Navigation("DecisionEvents");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("EmaBot.Api.Models.PaperTrade", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationCandidate", b =>
                {
                    b.Navigation("MarketResults");
                });

            modelBuilder.Entity("EmaBot.Api.Models.StrategyOptimizationRun", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
